-- Amiga realm core schema (ko2amiga_db). Ground truth + derived truth (A2 split).
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS `tournaments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) DEFAULT NULL,
  `name` varchar(50) NOT NULL,
  `chrono` double DEFAULT NULL,
  `event_date` date DEFAULT NULL,
  `is_cup` tinyint(1) NOT NULL DEFAULT 0,
  `country` varchar(50) DEFAULT NULL,
  `equal_teams` tinyint(1) NOT NULL DEFAULT 0,
  `player_count` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tournaments_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Ground truth: player identity
CREATE TABLE IF NOT EXISTS `amiga_players` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `country` varchar(50) NOT NULL DEFAULT '',
  `display` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_amiga_players_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Ground truth: canonical match results
CREATE TABLE IF NOT EXISTS `amiga_games` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_scores_id` int(11) NOT NULL,
  `game_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `player_a_id` int(11) NOT NULL,
  `player_b_id` int(11) NOT NULL,
  `tournament_id` int(11) DEFAULT NULL,
  `phase` varchar(50) DEFAULT NULL,
  `goals_a` int(11) NOT NULL,
  `goals_b` int(11) NOT NULL,
  `extra` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_amiga_games_source_scores_id` (`source_scores_id`),
  KEY `idx_amiga_games_date` (`game_date`),
  KEY `idx_amiga_games_player_a` (`player_a_id`),
  KEY `idx_amiga_games_player_b` (`player_b_id`),
  KEY `idx_amiga_games_tournament` (`tournament_id`),
  CONSTRAINT `fk_amiga_games_player_a` FOREIGN KEY (`player_a_id`) REFERENCES `amiga_players` (`id`),
  CONSTRAINT `fk_amiga_games_player_b` FOREIGN KEY (`player_b_id`) REFERENCES `amiga_players` (`id`),
  CONSTRAINT `fk_amiga_games_tournament` FOREIGN KEY (`tournament_id`) REFERENCES `tournaments` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Derived: per-game Elo and outcome flags (1:1 with amiga_games)
CREATE TABLE IF NOT EXISTS `amiga_game_ratings` (
  `game_id` int(11) NOT NULL,
  `rating_a` decimal(10,6) DEFAULT NULL,
  `rating_b` decimal(10,6) DEFAULT NULL,
  `rating_difference` decimal(10,6) DEFAULT NULL,
  `expected_score_a` decimal(10,6) DEFAULT NULL,
  `expected_score_b` decimal(10,6) DEFAULT NULL,
  `actual_score` decimal(10,6) DEFAULT NULL,
  `adjustment_a` decimal(10,6) DEFAULT NULL,
  `adjustment_b` decimal(10,6) DEFAULT NULL,
  `new_rating_a` decimal(10,6) DEFAULT NULL,
  `new_rating_b` decimal(10,6) DEFAULT NULL,
  `sum_of_goals` int(11) DEFAULT NULL,
  `goal_difference` int(11) DEFAULT NULL,
  `winner_id` int(11) DEFAULT NULL,
  `home_win` tinyint(4) DEFAULT NULL,
  `draw` tinyint(4) DEFAULT NULL,
  `away_win` tinyint(4) DEFAULT NULL,
  `dd_player_a` tinyint(4) DEFAULT NULL,
  `dd_player_b` tinyint(4) DEFAULT NULL,
  `cs_player_a` tinyint(4) DEFAULT NULL,
  `cs_player_b` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`game_id`),
  CONSTRAINT `fk_amiga_game_ratings_game` FOREIGN KEY (`game_id`) REFERENCES `amiga_games` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Derived: per-player career stats (column names match ladder replay output)
CREATE TABLE IF NOT EXISTS `amiga_player_stats` (
  `player_id` int(11) NOT NULL,
  `Display` mediumint(9) DEFAULT 0,
  `Rating` decimal(10,6) DEFAULT NULL,
  `NumberGames` mediumint(9) DEFAULT NULL,
  `NumberWins` mediumint(9) DEFAULT NULL,
  `NumberDraws` mediumint(9) DEFAULT NULL,
  `NumberLosses` mediumint(9) DEFAULT NULL,
  `WinRatio` decimal(5,4) DEFAULT NULL,
  `DrawRatio` decimal(5,4) DEFAULT NULL,
  `LossRatio` decimal(5,4) DEFAULT NULL,
  `GoalsFor` mediumint(9) DEFAULT NULL,
  `GoalsAgainst` mediumint(9) DEFAULT NULL,
  `AverageGoalsFor` decimal(6,4) DEFAULT NULL,
  `AverageGoalsAgainst` decimal(6,4) DEFAULT NULL,
  `GoalRatio` decimal(7,4) DEFAULT NULL,
  `MostGoalsScored` tinyint(4) DEFAULT NULL,
  `LeastGoalsScored` tinyint(4) NOT NULL DEFAULT 50,
  `MostGoalsConceded` tinyint(4) DEFAULT NULL,
  `LeastGoalsConceded` tinyint(4) NOT NULL DEFAULT 50,
  `BiggestWinDifference` tinyint(4) DEFAULT NULL,
  `BiggestDrawSum` tinyint(4) DEFAULT NULL,
  `BiggestLossDifference` tinyint(4) DEFAULT NULL,
  `SmallestSumOfGoals` tinyint(4) NOT NULL DEFAULT 50,
  `BiggestSumOfGoals` tinyint(4) DEFAULT NULL,
  `DoubleDigits` mediumint(9) DEFAULT NULL,
  `CleanSheets` mediumint(9) DEFAULT NULL,
  `DoubleDigitsConceded` mediumint(9) DEFAULT NULL,
  `CleanSheetsConceded` mediumint(9) DEFAULT NULL,
  `DoubleDigitsRatio` decimal(5,4) DEFAULT NULL,
  `CleanSheetsRatio` decimal(5,4) DEFAULT NULL,
  `DoubleDigitsConcededRatio` decimal(5,4) DEFAULT NULL,
  `CleanSheetsConcededRatio` decimal(5,4) DEFAULT NULL,
  `DifferentOpponents` smallint(6) DEFAULT NULL,
  `DifferentVictims` smallint(6) DEFAULT NULL,
  `DoubleDigitsVictims` smallint(6) DEFAULT NULL,
  `CleanSheetsVictims` smallint(6) DEFAULT NULL,
  `MostGoalsConcededVictims` smallint(6) DEFAULT NULL,
  `LeastGoalsScoredVictims` smallint(6) DEFAULT NULL,
  `BiggestLossVictims` smallint(6) DEFAULT NULL,
  `DifferentCulprits` smallint(6) DEFAULT NULL,
  `DoubleDigitsCulprits` smallint(6) DEFAULT NULL,
  `CleanSheetsCulprits` smallint(6) DEFAULT NULL,
  `MostGoalsScoredCulprits` smallint(6) DEFAULT NULL,
  `LeastGoalsConcededCulprits` smallint(6) DEFAULT NULL,
  `BiggestWinCulprits` smallint(6) DEFAULT NULL,
  `SumOfOpponentsRating` decimal(15,6) DEFAULT NULL,
  `AverageOpponentRating` decimal(7,3) DEFAULT NULL,
  `HighestRatedVictim` decimal(6,2) DEFAULT NULL,
  `LowestRatedCulprit` decimal(6,2) NOT NULL DEFAULT 5000.00,
  `CurrentRatingAscent` decimal(14,6) DEFAULT NULL,
  `BiggestRatingAscent` decimal(14,6) DEFAULT NULL,
  `CurrentRatingDescent` decimal(14,6) DEFAULT NULL,
  `BiggestRatingDescent` decimal(14,6) DEFAULT NULL,
  `LowestRating` decimal(10,6) NOT NULL DEFAULT 5000.00,
  `PeakRating` decimal(10,6) DEFAULT NULL,
  `WinningStreak` mediumint(9) DEFAULT NULL,
  `DrawingStreak` mediumint(9) DEFAULT NULL,
  `LosingStreak` mediumint(9) DEFAULT NULL,
  `NonWinStreak` mediumint(9) DEFAULT NULL,
  `NonDrawStreak` mediumint(9) DEFAULT NULL,
  `NonLossStreak` mediumint(9) DEFAULT NULL,
  `LongestWinningStreak` mediumint(9) DEFAULT NULL,
  `LongestDrawingStreak` mediumint(9) DEFAULT NULL,
  `LongestLosingStreak` mediumint(9) DEFAULT NULL,
  `LongestNonWinStreak` mediumint(9) DEFAULT NULL,
  `LongestNonDrawStreak` mediumint(9) DEFAULT NULL,
  `LongestNonLossStreak` mediumint(9) DEFAULT NULL,
  `ScoreStreak` mediumint(9) NOT NULL DEFAULT 0,
  `MerchantStreak` mediumint(9) NOT NULL DEFAULT 0,
  `ExactTenGoalStreak` mediumint(9) NOT NULL DEFAULT 0,
  `WinMarginOneStreak` mediumint(9) NOT NULL DEFAULT 0,
  `LossMarginOneStreak` mediumint(9) NOT NULL DEFAULT 0,
  `LastGame` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `LastGameGameID` int(11) DEFAULT NULL,
  `LastWinGameID` int(11) DEFAULT NULL,
  `LastDrawGameID` int(11) DEFAULT NULL,
  `LastLossGameID` int(11) DEFAULT NULL,
  `LowestRatingGameID` int(11) DEFAULT NULL,
  `PeakRatingGameID` int(11) DEFAULT NULL,
  `MostGoalsScoredGameID` int(11) DEFAULT NULL,
  `LeastGoalsScoredGameID` int(11) DEFAULT NULL,
  `MostGoalsConcededGameID` int(11) DEFAULT NULL,
  `LeastGoalsConcededGameID` int(11) DEFAULT NULL,
  `BiggestWinGameID` int(11) DEFAULT NULL,
  `BiggestDrawGameID` int(11) DEFAULT NULL,
  `BiggestLossGameID` int(11) DEFAULT NULL,
  `SmallestSumOfGoalsGameID` int(11) DEFAULT NULL,
  `BiggestSumOfGoalsGameID` int(11) DEFAULT NULL,
  `MostGoalsScoredVictimID` int(11) DEFAULT NULL,
  `LeastGoalsConcededVictimID` int(11) DEFAULT NULL,
  `BiggestWinVictimID` int(11) DEFAULT NULL,
  `MostGoalsConcededCulpritID` int(11) DEFAULT NULL,
  `LeastGoalsScoredCulpritID` int(11) DEFAULT NULL,
  `BiggestLossCulpritID` int(11) DEFAULT NULL,
  `HighestRatedVictimGameID` int(11) DEFAULT NULL,
  `LowestRatedCulpritGameID` int(11) DEFAULT NULL,
  PRIMARY KEY (`player_id`),
  CONSTRAINT `fk_amiga_player_stats_player` FOREIGN KEY (`player_id`) REFERENCES `amiga_players` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
