-- Server-wide hall-of-fame row (Amiga realm). Streak columns omitted per player-universe contract.
-- Apply after 012: mysql ko2amiga_db < scripts/amiga/sql/013_generalstats.sql
-- Populate: slice 11+ rebuild.

SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS `amiga_generalstats` (
  `id` tinyint(4) NOT NULL,
  `NumberOfPlayers` int(11) DEFAULT NULL,
  `DifferentOpponentsAverage` decimal(10,5) DEFAULT NULL,
  `GamesPlayed` int(11) DEFAULT NULL,
  `GamesPlayedAverage` decimal(10,3) DEFAULT NULL,
  `NumberOfDecidedGames` int(11) DEFAULT NULL,
  `NumberOfDraws` int(11) DEFAULT NULL,
  `DecidedGamesRatio` decimal(10,8) DEFAULT NULL,
  `DrawsRatio` decimal(10,8) DEFAULT NULL,
  `GoalsScored` int(11) DEFAULT NULL,
  `GoalsPerGameAverage` decimal(10,7) DEFAULT NULL,
  `DoubleDigits` int(11) DEFAULT NULL,
  `CleanSheets` int(11) DEFAULT NULL,
  `DoubleDigitsRatio` decimal(10,8) DEFAULT NULL,
  `CleanSheetsRatio` decimal(10,8) DEFAULT NULL,
  `MostGamesPlayed` int(11) DEFAULT NULL,
  `MostWins` int(11) DEFAULT NULL,
  `MostGoalsScored` int(11) DEFAULT NULL,
  `MostGoalsScoredInOneGame` int(11) DEFAULT NULL,
  `BiggestWinDifference` int(11) DEFAULT NULL,
  `BiggestDrawSum` int(11) DEFAULT NULL,
  `BiggestSumOfGoals` int(11) DEFAULT NULL,
  `MostDoubleDigits` int(11) DEFAULT NULL,
  `MostCleanSheets` int(11) DEFAULT NULL,
  `MostDifferentOpponents` int(11) DEFAULT NULL,
  `MostDifferentVictims` int(11) DEFAULT NULL,
  `MostDoubleDigitsVictims` int(11) DEFAULT NULL,
  `MostCleanSheetsVictims` int(11) DEFAULT NULL,
  `BiggestRatingAscent` decimal(10,5) DEFAULT NULL,
  `BiggestPeakRating` decimal(10,6) DEFAULT NULL,
  `MostGamesPlayedID` int(11) DEFAULT NULL,
  `MostWinsID` int(11) DEFAULT NULL,
  `MostGoalsScoredID` int(11) DEFAULT NULL,
  `MostGoalsScoredInOneGameID` int(11) DEFAULT NULL,
  `BiggestWinDifferenceID` int(11) DEFAULT NULL,
  `BiggestDrawSumIDA` int(11) DEFAULT NULL,
  `BiggestDrawSumIDB` int(11) DEFAULT NULL,
  `BiggestSumOfGoalsIDA` int(11) DEFAULT NULL,
  `BiggestSumOfGoalsIDB` int(11) DEFAULT NULL,
  `MostDoubleDigitsID` int(11) DEFAULT NULL,
  `MostCleanSheetsID` int(11) DEFAULT NULL,
  `MostDifferentOpponentsID` int(11) DEFAULT NULL,
  `MostDifferentVictimsID` int(11) DEFAULT NULL,
  `MostDoubleDigitsVictimsID` int(11) DEFAULT NULL,
  `MostCleanSheetsVictimsID` int(11) DEFAULT NULL,
  `BiggestRatingAscentID` int(11) DEFAULT NULL,
  `BiggestPeakRatingID` int(11) DEFAULT NULL,
  `MostGamesPlayedName` varchar(50) DEFAULT NULL,
  `MostWinsName` varchar(50) DEFAULT NULL,
  `MostGoalsScoredName` varchar(50) DEFAULT NULL,
  `MostGoalsScoredInOneGameName` varchar(50) DEFAULT NULL,
  `BiggestWinDifferenceName` varchar(50) DEFAULT NULL,
  `BiggestDrawSumNameA` varchar(50) DEFAULT NULL,
  `BiggestDrawSumNameB` varchar(50) DEFAULT NULL,
  `BiggestSumOfGoalsNameA` varchar(50) DEFAULT NULL,
  `BiggestSumOfGoalsNameB` varchar(50) DEFAULT NULL,
  `MostDoubleDigitsName` varchar(50) DEFAULT NULL,
  `MostCleanSheetsName` varchar(50) DEFAULT NULL,
  `MostDifferentOpponentsName` varchar(50) DEFAULT NULL,
  `MostDifferentVictimsName` varchar(50) DEFAULT NULL,
  `MostDoubleDigitsVictimsName` varchar(50) DEFAULT NULL,
  `MostCleanSheetsVictimsName` varchar(50) DEFAULT NULL,
  `BiggestRatingAscentName` varchar(50) DEFAULT NULL,
  `BiggestPeakRatingName` varchar(50) DEFAULT NULL,
  `MostGamesPlayedDate` mediumtext DEFAULT NULL,
  `MostWinsDate` mediumtext DEFAULT NULL,
  `MostGoalsScoredDate` mediumtext DEFAULT NULL,
  `MostGoalsScoredInOneGameDate` mediumtext DEFAULT NULL,
  `BiggestWinDifferenceDate` mediumtext DEFAULT NULL,
  `BiggestDrawSumDate` mediumtext DEFAULT NULL,
  `BiggestSumOfGoalsDate` mediumtext DEFAULT NULL,
  `MostDoubleDigitsDate` mediumtext DEFAULT NULL,
  `MostCleanSheetsDate` mediumtext DEFAULT NULL,
  `MostDifferentOpponentsDate` mediumtext DEFAULT NULL,
  `MostDifferentVictimsDate` mediumtext DEFAULT NULL,
  `MostDoubleDigitsVictimsDate` mediumtext DEFAULT NULL,
  `MostCleanSheetsVictimsDate` mediumtext DEFAULT NULL,
  `BiggestRatingAscentDate` mediumtext DEFAULT NULL,
  `BiggestPeakRatingDate` mediumtext DEFAULT NULL,
  `MostGoalsScoredInOneGameGameID` int(11) DEFAULT NULL,
  `BiggestWinDifferenceGameID` int(11) DEFAULT NULL,
  `BiggestDrawSumGameID` int(11) DEFAULT NULL,
  `BiggestSumOfGoalsGameID` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT IGNORE INTO `amiga_generalstats` (`id`) VALUES (1);
