-- Realm timeline: full amiga_generalstats payload per finalized tournament.
-- Policy: docs/amiga-realm-snapshot-policy.md
-- Apply after 026: mysql ko2amiga_db < scripts/amiga/sql/027_realm_snapshots.sql

SET time_zone = '+00:00';

ALTER TABLE `amiga_generalstats`
  ADD COLUMN `BiggestWinRatio` decimal(5,4) DEFAULT NULL,
  ADD COLUMN `BiggestWinRatioID` int(11) DEFAULT NULL,
  ADD COLUMN `BiggestWinRatioName` varchar(50) DEFAULT NULL,
  ADD COLUMN `BiggestGoalsForAverage` decimal(6,4) DEFAULT NULL,
  ADD COLUMN `BiggestGoalsForAverageID` int(11) DEFAULT NULL,
  ADD COLUMN `BiggestGoalsForAverageName` varchar(50) DEFAULT NULL,
  ADD COLUMN `SmallestGoalsAgainstAverage` decimal(6,4) DEFAULT NULL,
  ADD COLUMN `SmallestGoalsAgainstAverageID` int(11) DEFAULT NULL,
  ADD COLUMN `SmallestGoalsAgainstAverageName` varchar(50) DEFAULT NULL,
  ADD COLUMN `BiggestGoalRatio` decimal(7,4) DEFAULT NULL,
  ADD COLUMN `BiggestGoalRatioID` int(11) DEFAULT NULL,
  ADD COLUMN `BiggestGoalRatioName` varchar(50) DEFAULT NULL,
  ADD COLUMN `BiggestDoubleDigitsRatio` decimal(5,4) DEFAULT NULL,
  ADD COLUMN `BiggestDoubleDigitsRatioID` int(11) DEFAULT NULL,
  ADD COLUMN `BiggestDoubleDigitsRatioName` varchar(50) DEFAULT NULL,
  ADD COLUMN `BiggestCleanSheetsRatio` decimal(5,4) DEFAULT NULL,
  ADD COLUMN `BiggestCleanSheetsRatioID` int(11) DEFAULT NULL,
  ADD COLUMN `BiggestCleanSheetsRatioName` varchar(50) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS `amiga_realm_snapshots` (
  `tournament_id` int(11) NOT NULL,
  `event_date` date DEFAULT NULL,
  `event_chrono` double DEFAULT NULL,
  `tournament_name` varchar(50) NOT NULL,
  `finalized_at` datetime NOT NULL,
  `NumberOfPlayers` int(11) DEFAULT NULL,
  `DifferentOpponentsAverage` decimal(10,5) DEFAULT NULL,
  `GamesPlayed` int(11) DEFAULT NULL,
  `GamesPlayedAverage` decimal(10,3) DEFAULT NULL,
  `NumberOfDecidedGames` int(11) DEFAULT NULL,
  `NumberOfDraws` int(11) DEFAULT NULL,
  `DecidedGamesRatio` decimal(10,8) DEFAULT NULL,
  `DrawsRatio` decimal(10,8) DEFAULT NULL,
  `GoalsScored` int(11) DEFAULT NULL,
  `GoalsPerGameAverage` decimal(10,7) DEFAULT NULL,
  `DoubleDigits` int(11) DEFAULT NULL,
  `CleanSheets` int(11) DEFAULT NULL,
  `DoubleDigitsRatio` decimal(10,8) DEFAULT NULL,
  `CleanSheetsRatio` decimal(10,8) DEFAULT NULL,
  `MostGamesPlayed` int(11) DEFAULT NULL,
  `MostWins` int(11) DEFAULT NULL,
  `MostGoalsScored` int(11) DEFAULT NULL,
  `MostGoalsScoredInOneGame` int(11) DEFAULT NULL,
  `BiggestWinDifference` int(11) DEFAULT NULL,
  `BiggestDrawSum` int(11) DEFAULT NULL,
  `BiggestSumOfGoals` int(11) DEFAULT NULL,
  `MostDoubleDigits` int(11) DEFAULT NULL,
  `MostCleanSheets` int(11) DEFAULT NULL,
  `MostDifferentOpponents` int(11) DEFAULT NULL,
  `MostDifferentVictims` int(11) DEFAULT NULL,
  `MostDoubleDigitsVictims` int(11) DEFAULT NULL,
  `MostCleanSheetsVictims` int(11) DEFAULT NULL,
  `BiggestRatingAscent` decimal(10,5) DEFAULT NULL,
  `BiggestPeakRating` decimal(10,6) DEFAULT NULL,
  `MostGamesPlayedID` int(11) DEFAULT NULL,
  `MostWinsID` int(11) DEFAULT NULL,
  `MostGoalsScoredID` int(11) DEFAULT NULL,
  `MostGoalsScoredInOneGameID` int(11) DEFAULT NULL,
  `BiggestWinDifferenceID` int(11) DEFAULT NULL,
  `BiggestDrawSumIDA` int(11) DEFAULT NULL,
  `BiggestDrawSumIDB` int(11) DEFAULT NULL,
  `BiggestSumOfGoalsIDA` int(11) DEFAULT NULL,
  `BiggestSumOfGoalsIDB` int(11) DEFAULT NULL,
  `MostDoubleDigitsID` int(11) DEFAULT NULL,
  `MostCleanSheetsID` int(11) DEFAULT NULL,
  `MostDifferentOpponentsID` int(11) DEFAULT NULL,
  `MostDifferentVictimsID` int(11) DEFAULT NULL,
  `MostDoubleDigitsVictimsID` int(11) DEFAULT NULL,
  `MostCleanSheetsVictimsID` int(11) DEFAULT NULL,
  `BiggestRatingAscentID` int(11) DEFAULT NULL,
  `BiggestPeakRatingID` int(11) DEFAULT NULL,
  `MostGamesPlayedName` varchar(50) DEFAULT NULL,
  `MostWinsName` varchar(50) DEFAULT NULL,
  `MostGoalsScoredName` varchar(50) DEFAULT NULL,
  `MostGoalsScoredInOneGameName` varchar(50) DEFAULT NULL,
  `BiggestWinDifferenceName` varchar(50) DEFAULT NULL,
  `BiggestDrawSumNameA` varchar(50) DEFAULT NULL,
  `BiggestDrawSumNameB` varchar(50) DEFAULT NULL,
  `BiggestSumOfGoalsNameA` varchar(50) DEFAULT NULL,
  `BiggestSumOfGoalsNameB` varchar(50) DEFAULT NULL,
  `MostDoubleDigitsName` varchar(50) DEFAULT NULL,
  `MostCleanSheetsName` varchar(50) DEFAULT NULL,
  `MostDifferentOpponentsName` varchar(50) DEFAULT NULL,
  `MostDifferentVictimsName` varchar(50) DEFAULT NULL,
  `MostDoubleDigitsVictimsName` varchar(50) DEFAULT NULL,
  `MostCleanSheetsVictimsName` varchar(50) DEFAULT NULL,
  `BiggestRatingAscentName` varchar(50) DEFAULT NULL,
  `BiggestPeakRatingName` varchar(50) DEFAULT NULL,
  `MostGamesPlayedDate` mediumtext DEFAULT NULL,
  `MostWinsDate` mediumtext DEFAULT NULL,
  `MostGoalsScoredDate` mediumtext DEFAULT NULL,
  `MostGoalsScoredInOneGameDate` mediumtext DEFAULT NULL,
  `BiggestWinDifferenceDate` mediumtext DEFAULT NULL,
  `BiggestDrawSumDate` mediumtext DEFAULT NULL,
  `BiggestSumOfGoalsDate` mediumtext DEFAULT NULL,
  `MostDoubleDigitsDate` mediumtext DEFAULT NULL,
  `MostCleanSheetsDate` mediumtext DEFAULT NULL,
  `MostDifferentOpponentsDate` mediumtext DEFAULT NULL,
  `MostDifferentVictimsDate` mediumtext DEFAULT NULL,
  `MostDoubleDigitsVictimsDate` mediumtext DEFAULT NULL,
  `MostCleanSheetsVictimsDate` mediumtext DEFAULT NULL,
  `BiggestRatingAscentDate` mediumtext DEFAULT NULL,
  `BiggestPeakRatingDate` mediumtext DEFAULT NULL,
  `MostGoalsScoredInOneGameGameID` int(11) DEFAULT NULL,
  `BiggestWinDifferenceGameID` int(11) DEFAULT NULL,
  `BiggestDrawSumGameID` int(11) DEFAULT NULL,
  `BiggestSumOfGoalsGameID` int(11) DEFAULT NULL,
  `BiggestWinRatio` decimal(5,4) DEFAULT NULL,
  `BiggestWinRatioID` int(11) DEFAULT NULL,
  `BiggestWinRatioName` varchar(50) DEFAULT NULL,
  `BiggestGoalsForAverage` decimal(6,4) DEFAULT NULL,
  `BiggestGoalsForAverageID` int(11) DEFAULT NULL,
  `BiggestGoalsForAverageName` varchar(50) DEFAULT NULL,
  `SmallestGoalsAgainstAverage` decimal(6,4) DEFAULT NULL,
  `SmallestGoalsAgainstAverageID` int(11) DEFAULT NULL,
  `SmallestGoalsAgainstAverageName` varchar(50) DEFAULT NULL,
  `BiggestGoalRatio` decimal(7,4) DEFAULT NULL,
  `BiggestGoalRatioID` int(11) DEFAULT NULL,
  `BiggestGoalRatioName` varchar(50) DEFAULT NULL,
  `BiggestDoubleDigitsRatio` decimal(5,4) DEFAULT NULL,
  `BiggestDoubleDigitsRatioID` int(11) DEFAULT NULL,
  `BiggestDoubleDigitsRatioName` varchar(50) DEFAULT NULL,
  `BiggestCleanSheetsRatio` decimal(5,4) DEFAULT NULL,
  `BiggestCleanSheetsRatioID` int(11) DEFAULT NULL,
  `BiggestCleanSheetsRatioName` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`tournament_id`),
  KEY `idx_realm_snapshots_chrono` (`event_date`, `event_chrono`, `tournament_id`),
  CONSTRAINT `fk_realm_snapshots_tournament`
    FOREIGN KEY (`tournament_id`) REFERENCES `tournaments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
