#!/usr/bin/env python3
"""Generate player_milestones_rebuild_exists.sql from probe specs."""
from pathlib import Path

SPECS = [
    ("brace", 2, "gf >= 2"),
    ("hat_trick", 3, "gf >= 3"),
    ("five_goal_frenzy", 5, "gf >= 5"),
    ("eight_goal_storm", 8, "gf >= 8"),
    ("dozen_dash", 12, "gf >= 12"),
    ("filthy_fifteen", 15, "gf >= 15"),
    ("victim_of_commerce", 10, "ga >= 10"),
    ("minimalist", 1, "sc = 1 AND gf = 1 AND ga = 0"),
    ("perfect_storm", 10, "sc = 1 AND gf = 10 AND ga = 0"),
    ("battle_hardened", 10, "sc = 0.5 AND gf + ga >= 10 AND gf = ga"),
    ("survivor", 7, "sc = 1 AND ga >= 7"),
    ("goal_fest_draw", 14, "sc = 0.5 AND gf + ga >= 14"),
    ("comfortable", 5, "sc = 1 AND (gf - ga) >= 5"),
    ("ruthless", 10, "sc = 1 AND (gf - ga) >= 10"),
    ("hard_lesson", 10, "sc = 0 AND (ga - gf) >= 10"),
    ("twenty_goal_chaos", 20, "gf + ga >= 20"),
    ("massive_upset", 500, "sc = 1 AND (r_opp - r_pre) >= 500"),
    ("merchant_denied", 9, "sc = 0 AND gf = 9 AND ga = 10"),
    ("merchant_trade_fair", 10, "sc = 0.5 AND gf = 10 AND ga = 10"),
    ("leaky_merchant", 10, "sc = 1 AND gf >= 10 AND ga = 9"),
]
SKIP = frozenset({"dd_merchant_10", "six_goal_draw"})
SIDES = """
    SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
"""

OUT = Path(__file__).resolve().parents[2] / "docs" / "archive" / "batch-rebuild-sql-2026-05" / "player_milestones_rebuild_exists.sql"


def main() -> None:
    parts = [
        "-- Generated by scripts/oneoff/gen_milestone_exists_sql.py — do not hand-edit.",
        "-- First rated game per player matching condition.",
        "",
    ]
    for mk, val, cond in SPECS:
        if mk in SKIP:
            continue
        parts.extend(
            [
                "INSERT INTO `player_milestones` (",
                "  `player_id`, `milestone_key`, `achieved_at`, `value`,",
                "  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`",
                ")",
                "SELECT",
                f"  ranked.player_id, '{mk}', ranked.`Date`, {val},",
                "  'game', ranked.game_id, NULL, NULL, NULL",
                "FROM (",
                "  SELECT pid AS player_id, game_id, `Date`,",
                "         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn",
                "  FROM (",
                SIDES.strip(),
                f"  ) s WHERE {cond}",
                ") ranked",
                "INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1",
                "WHERE rn = 1;",
                "",
            ]
        )
    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(SPECS) - len(SKIP)} inserts)")


if __name__ == "__main__":
    main()
