#!/usr/bin/env python3
"""
Generate player_milestones_rebuild_year_in_heaven.sql — first calendar year with all
52 UTC week slots played (profile played-weeks grid).

Unlock game = MIN(ratedresults.id) on the week Monday that completes the 52/52 set.

Regenerate: python scripts/oneoff/gen_milestone_year_in_heaven_sql.py
"""
from __future__ import annotations

import sys
from collections import defaultdict
from datetime import date, datetime, timedelta
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from scripts.k2_rating_core.config import load_db_config  # noqa: E402
from scripts.k2_rating_core.connection import connect  # noqa: E402

OUT = _REPO / "docs" / "archive" / "batch-rebuild-sql-2026-05" / "player_milestones_rebuild_year_in_heaven.sql"
KEY = "year_in_heaven"
WEEKS_PER_YEAR = 52


def calendar_year_week_mondays(year: int) -> list[date]:
    jan1 = date(year, 1, 1)
    week1 = jan1 - timedelta(days=jan1.weekday())
    return [week1 + timedelta(days=7 * i) for i in range(WEEKS_PER_YEAR)]


def calendar_year_for_week_monday(monday: date) -> int | None:
    for y in (monday.year - 1, monday.year, monday.year + 1):
        if monday in calendar_year_week_mondays(y):
            return y
    return None


def establishing_game(cur, player_id: int, week_monday: date) -> tuple[int, datetime] | None:
    cur.execute(
        """
        SELECT MIN(id) AS game_id FROM (
          SELECT id FROM ratedresults
          WHERE idA = %s AND DATE_SUB(DATE(`Date`), INTERVAL WEEKDAY(`Date`) DAY) = %s
          UNION ALL
          SELECT id FROM ratedresults
          WHERE idB = %s AND DATE_SUB(DATE(`Date`), INTERVAL WEEKDAY(`Date`) DAY) = %s
        ) AS g
        """,
        (player_id, week_monday, player_id, week_monday),
    )
    row = cur.fetchone()
    if not row or row["game_id"] is None:
        return None
    gid = int(row["game_id"])
    cur.execute("SELECT `Date` FROM ratedresults WHERE id = %s", (gid,))
    dt_row = cur.fetchone()
    if not dt_row:
        return None
    dt = dt_row["Date"]
    if not isinstance(dt, datetime):
        return None
    return gid, dt


def main() -> None:
    con = connect(load_db_config(), dry_run=False)
    cur = con.cursor()
    cur.execute("SET time_zone = '+00:00'")
    cur.execute(
        """
        SELECT player_id, period_start
        FROM player_period_games
        WHERE period_type = 'week'
        ORDER BY player_id ASC, period_start ASC
        """
    )

    unlock_rows: list[tuple[int, datetime, int, int]] = []
    current_pid: int | None = None
    week_dates: list[date] = []
    covered: dict[int, set[date]] = defaultdict(set)

    def flush_player(pid: int) -> None:
        nonlocal week_dates, covered
        if not week_dates:
            week_dates = []
            covered = defaultdict(set)
            return
        for w in week_dates:
            y = calendar_year_for_week_monday(w)
            if y is None:
                continue
            covered[y].add(w)
            if len(covered[y]) == WEEKS_PER_YEAR:
                est = establishing_game(cur, pid, w)
                if est:
                    unlock_rows.append((pid, est[1], est[0], y))
                break
        week_dates = []
        covered = defaultdict(set)

    for row in cur.fetchall():
        pid = int(row["player_id"])
        ps = row["period_start"]
        if isinstance(ps, datetime):
            w = ps.date()
        else:
            w = date.fromisoformat(str(ps)[:10])

        if current_pid is not None and pid != current_pid:
            flush_player(current_pid)
        current_pid = pid
        week_dates.append(w)

    if current_pid is not None:
        flush_player(current_pid)

    cur.close()
    con.close()

    lines = [
        "-- Generated by scripts/oneoff/gen_milestone_year_in_heaven_sql.py",
        f"-- {KEY}: first calendar year with a rated game in all 52 UTC week slots.",
        "",
    ]
    for pid, dt, gid, val in unlock_rows:
        ts = dt.strftime("%Y-%m-%d %H:%M:%S")
        lines.append(
            f"INSERT INTO `player_milestones` "
            f"(`player_id`, `milestone_key`, `achieved_at`, `value`, "
            f"`source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) "
            f"VALUES ({pid}, '{KEY}', '{ts}', {val}, 'game', {gid}, NULL, NULL, NULL);"
        )
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(unlock_rows)} unlock rows)")


if __name__ == "__main__":
    main()
