#!/usr/bin/env python3
"""
Generate player_milestones_rebuild_play_streak_100.sql — first time a player
reaches 100 consecutive UTC calendar days with ≥1 rated game.

Unlock game = MIN(ratedresults.id) on the 100th day of that run (establishing game).

Regenerate: python scripts/oneoff/gen_milestone_play_streak_100_sql.py
"""
from __future__ import annotations

import sys
from datetime import date, datetime, timedelta
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from scripts.k2_rating_core.config import load_db_config  # noqa: E402
from scripts.k2_rating_core.connection import connect  # noqa: E402

OUT = _REPO / "docs" / "archive" / "batch-rebuild-sql-2026-05" / "player_milestones_rebuild_play_streak_100.sql"
THRESHOLD = 100
KEY = "play_streak_100"


def next_day(d: date) -> date:
    return d + timedelta(days=1)


def establishing_game(cur, player_id: int, day: date) -> tuple[int, datetime] | None:
    cur.execute(
        """
        SELECT MIN(id) AS game_id FROM (
          SELECT id FROM ratedresults WHERE idA = %s AND DATE(`Date`) = %s
          UNION ALL
          SELECT id FROM ratedresults WHERE idB = %s AND DATE(`Date`) = %s
        ) AS g
        """,
        (player_id, day, player_id, day),
    )
    row = cur.fetchone()
    if not row or row["game_id"] is None:
        return None
    gid = int(row["game_id"])
    cur.execute("SELECT `Date` FROM ratedresults WHERE id = %s", (gid,))
    dt_row = cur.fetchone()
    if not dt_row:
        return None
    dt = dt_row["Date"]
    if not isinstance(dt, datetime):
        return None
    return gid, dt


def process_player_days(cur, player_id: int, days: list[date]) -> tuple[int, datetime, int, int] | None:
    if not days:
        return None
    run = [days[0]]
    for i in range(1, len(days)):
        if days[i] == next_day(run[-1]):
            run.append(days[i])
            if len(run) == THRESHOLD:
                est = establishing_game(cur, player_id, run[-1])
                if est:
                    return player_id, est[1], est[0], THRESHOLD
        else:
            run = [days[i]]
            if len(run) == THRESHOLD:
                est = establishing_game(cur, player_id, run[-1])
                if est:
                    return player_id, est[1], est[0], THRESHOLD
    return None


def main() -> None:
    con = connect(load_db_config(), dry_run=False)
    cur = con.cursor()
    cur.execute("SET time_zone = '+00:00'")
    cur.execute(
        """
        SELECT player_id, period_start
        FROM player_period_games
        WHERE period_type = 'day'
        ORDER BY player_id ASC, period_start ASC
        """
    )
    rows: list[tuple[int, datetime, int, int]] = []
    current_pid: int | None = None
    days: list[date] = []

    for row in cur.fetchall():
        pid = int(row["player_id"])
        ps = row["period_start"]
        if isinstance(ps, datetime):
            day = ps.date()
        else:
            day = date.fromisoformat(str(ps)[:10])

        if current_pid is not None and pid != current_pid:
            hit = process_player_days(cur, current_pid, days)
            if hit:
                rows.append(hit)
            days = []
        current_pid = pid
        days.append(day)

    if current_pid is not None:
        hit = process_player_days(cur, current_pid, days)
        if hit:
            rows.append(hit)

    cur.close()
    con.close()

    lines = [
        "-- Generated by scripts/oneoff/gen_milestone_play_streak_100_sql.py",
        f"-- {KEY}: first cross of {THRESHOLD} consecutive UTC days with a rated game.",
        "",
    ]
    for pid, dt, gid, val in rows:
        ts = dt.strftime("%Y-%m-%d %H:%M:%S")
        lines.append(
            f"INSERT INTO `player_milestones` "
            f"(`player_id`, `milestone_key`, `achieved_at`, `value`, "
            f"`source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) "
            f"VALUES ({pid}, '{KEY}', '{ts}', {val}, 'game', {gid}, NULL, NULL, NULL);"
        )
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    holders = len(rows)
    print(f"Wrote {OUT} ({holders} unlock rows)")


if __name__ == "__main__":
    main()
