#!/usr/bin/env python3
"""
Generate player_milestones_rebuild_streaks.sql — first chronological cross + source_game_id.

Win/loss/draw streak milestones (not playertable max alone).
Regenerate: python scripts/oneoff/gen_milestone_streak_sql.py
"""
from __future__ import annotations

import sys
from dataclasses import dataclass, field
from datetime import date, datetime
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from scripts.ladder.config import load_db_config  # noqa: E402
from scripts.ladder.engine import connect  # noqa: E402

OUT = _REPO / "scripts" / "ladder" / "sql" / "archive" / "batch-2026-05" / "player_milestones_rebuild_streaks.sql"

# (milestone_key, streak_kind, threshold, value column)
SPECS: list[tuple[str, str, int, int]] = [
    ("win_hat_trick", "win", 3, 3),
    ("ten_wins_straight", "win", 10, 10),
    ("rampage", "win", 15, 15),
    ("win_streak_30", "win", 30, 30),
    ("cold_streak", "loss", 5, 5),
    ("win_drought", "non_win", 10, 10),
    ("peace_streak", "draw", 3, 3),
    ("ten_wins", "career_wins", 10, 10),
]


@dataclass
class PlayerStreak:
    win: int = 0
    loss: int = 0
    non_win: int = 0
    draw: int = 0
    career_wins: int = 0
    done: set[str] = field(default_factory=set)


def main() -> None:
    con = connect(load_db_config(), dry_run=False)
    cur = con.cursor()
    cur.execute("SET time_zone = '+00:00'")
    cur.execute("SELECT ID FROM playertable WHERE NumberGames >= 1")
    eligible = {int(r["ID"]) for r in cur.fetchall()}
    cur.execute(
        """
        SELECT id, `Date`, idA, idB, GoalsA, GoalsB, ActualScore
        FROM ratedresults
        ORDER BY `Date` ASC, id ASC
        """
    )
    games = cur.fetchall()
    players: dict[int, PlayerStreak] = {}
    rows: list[tuple[int, str, datetime, int, int]] = []

    for g in games:
        gid = int(g["id"])
        dt = g["Date"]
        if not isinstance(dt, datetime):
            continue
        id_a, id_b = int(g["idA"]), int(g["idB"])
        sc = float(g["ActualScore"])

        for pid, won, drew, lost in (
            (id_a, sc == 1.0, sc == 0.5, sc == 0.0),
            (id_b, sc == 0.0, sc == 0.5, sc == 1.0),
        ):
            if pid not in eligible:
                continue
            st = players.setdefault(pid, PlayerStreak())

            if won:
                st.win += 1
                st.loss = 0
                st.non_win = 0
                st.draw = 0
                st.career_wins += 1
            elif drew:
                st.win = 0
                st.loss = 0
                st.non_win += 1
                st.draw += 1
            elif lost:
                st.win = 0
                st.loss += 1
                st.non_win += 1
                st.draw = 0

            for key, kind, thresh, val in SPECS:
                if key in st.done:
                    continue
                if kind == "career_wins":
                    ok = st.career_wins >= thresh
                else:
                    ok = {
                        "win": st.win,
                        "loss": st.loss,
                        "non_win": st.non_win,
                        "draw": st.draw,
                    }[kind] >= thresh
                if not ok:
                    continue
                st.done.add(key)
                rows.append((pid, key, dt, val, gid))

    con.close()

    lines = [
        "-- Generated by scripts/oneoff/gen_milestone_streak_sql.py",
        "-- Chronological first streak cross; source_kind=game.",
        "",
    ]
    for pid, mk, dt, val, gid in rows:
        ts = dt.strftime("%Y-%m-%d %H:%M:%S")
        lines.append(
            f"INSERT INTO `player_milestones` "
            f"(`player_id`, `milestone_key`, `achieved_at`, `value`, "
            f"`source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) "
            f"VALUES ({pid}, '{mk}', '{ts}', {val}, 'game', {gid}, NULL, NULL, NULL);"
        )
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(rows)} rows, {len({r[1] for r in rows})} keys)")


if __name__ == "__main__":
    main()
