-- Generated by scripts/oneoff/gen_milestone_exists_sql.py — do not hand-edit.
-- First rated game per player matching condition.

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'brace', ranked.`Date`, 2,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE gf >= 2
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'hat_trick', ranked.`Date`, 3,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE gf >= 3
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'five_goal_frenzy', ranked.`Date`, 5,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE gf >= 5
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'eight_goal_storm', ranked.`Date`, 8,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE gf >= 8
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'dozen_dash', ranked.`Date`, 12,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE gf >= 12
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'filthy_fifteen', ranked.`Date`, 15,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE gf >= 15
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'victim_of_commerce', ranked.`Date`, 10,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE ga >= 10
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'minimalist', ranked.`Date`, 1,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE sc = 1 AND gf = 1 AND ga = 0
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'perfect_storm', ranked.`Date`, 10,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE sc = 1 AND gf = 10 AND ga = 0
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'battle_hardened', ranked.`Date`, 10,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE sc = 0.5 AND gf + ga >= 10 AND gf = ga
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'survivor', ranked.`Date`, 7,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE sc = 1 AND ga >= 7
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'goal_fest_draw', ranked.`Date`, 14,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE sc = 0.5 AND gf + ga >= 14
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'comfortable', ranked.`Date`, 5,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE sc = 1 AND (gf - ga) >= 5
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'ruthless', ranked.`Date`, 10,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE sc = 1 AND (gf - ga) >= 10
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'hard_lesson', ranked.`Date`, 10,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE sc = 0 AND (ga - gf) >= 10
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'twenty_goal_chaos', ranked.`Date`, 20,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE gf + ga >= 20
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'massive_upset', ranked.`Date`, 500,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE sc = 1 AND (r_opp - r_pre) >= 500
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'merchant_denied', ranked.`Date`, 9,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE sc = 0 AND gf = 9 AND ga = 10
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'merchant_trade_fair', ranked.`Date`, 10,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE sc = 0.5 AND gf = 10 AND ga = 10
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

INSERT INTO `player_milestones` (
  `player_id`, `milestone_key`, `achieved_at`, `value`,
  `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`
)
SELECT
  ranked.player_id, 'leaky_merchant', ranked.`Date`, 10,
  'game', ranked.game_id, NULL, NULL, NULL
FROM (
  SELECT pid AS player_id, game_id, `Date`,
         ROW_NUMBER() OVER (PARTITION BY pid ORDER BY `Date` ASC, game_id ASC) AS rn
  FROM (
SELECT id AS game_id, idA AS pid, `Date`, GoalsA AS gf, GoalsB AS ga, ActualScore AS sc,
      RatingA AS r_pre, RatingB AS r_opp
    FROM ratedresults
    UNION ALL
    SELECT id, idB, `Date`, GoalsB, GoalsA,
      CASE WHEN ActualScore = 1 THEN 0 WHEN ActualScore = 0 THEN 1 ELSE 0.5 END,
      RatingB, RatingA
    FROM ratedresults
  ) s WHERE sc = 1 AND gf >= 10 AND ga = 9
) ranked
INNER JOIN `playertable` pt ON pt.`ID` = ranked.player_id AND pt.`NumberGames` >= 1
WHERE rn = 1;

