-- Player event snapshots + present projection (event-snapshot policy slice 1).
-- Apply after 023: mysql ko2amiga_db < scripts/amiga/sql/024_player_snapshots.sql
-- Policy: docs/amiga-event-snapshot-policy.md
-- Populated: finalize writer + replay backfill (slices 3–4). Legacy tables coexist until slice 8.

SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS `amiga_player_event_snapshots` (
  `player_id` int(11) NOT NULL,
  `tournament_id` int(11) NOT NULL,
  `event_date` date DEFAULT NULL,
  `event_chrono` double DEFAULT NULL,
  `tournament_name` varchar(50) NOT NULL,
  `is_cup` tinyint(1) NOT NULL DEFAULT 0,
  `country` varchar(50) DEFAULT NULL,
  `has_league` tinyint(1) NOT NULL DEFAULT 0,
  `has_cup` tinyint(1) NOT NULL DEFAULT 0,
  `finalized_at` datetime NOT NULL,
  -- Event-local (this tournament; mirrors amiga_player_tournament_participation)
  `event_finish_position` smallint DEFAULT NULL,
  `event_points` smallint(6) NOT NULL DEFAULT 0,
  `games` smallint(6) NOT NULL DEFAULT 0,
  `wins` smallint(6) NOT NULL DEFAULT 0,
  `draws` smallint(6) NOT NULL DEFAULT 0,
  `losses` smallint(6) NOT NULL DEFAULT 0,
  `goals_for` smallint(6) NOT NULL DEFAULT 0,
  `goals_against` smallint(6) NOT NULL DEFAULT 0,
  `avg_goals_for` decimal(6,4) DEFAULT NULL,
  `avg_goals_against` decimal(6,4) DEFAULT NULL,
  `rating_before` decimal(10,6) DEFAULT NULL,
  `rating_delta` decimal(10,6) DEFAULT NULL,
  `rating_after` decimal(10,6) DEFAULT NULL,
  `performance_rating` decimal(10,6) DEFAULT NULL,
  `games_in_event` smallint(6) NOT NULL DEFAULT 0,
  `is_winner` tinyint(1) NOT NULL DEFAULT 0,
  `best_knockout_phase` varchar(50) DEFAULT NULL,
  -- Career cumulative (mirrors amiga_player_stats / PlayerState.to_db_row)
  `Display` mediumint(9) DEFAULT 0,
  `Rating` decimal(10,6) DEFAULT NULL,
  `NumberGames` mediumint(9) DEFAULT NULL,
  `NumberWins` mediumint(9) DEFAULT NULL,
  `NumberDraws` mediumint(9) DEFAULT NULL,
  `NumberLosses` mediumint(9) DEFAULT NULL,
  `WinRatio` decimal(5,4) DEFAULT NULL,
  `DrawRatio` decimal(5,4) DEFAULT NULL,
  `LossRatio` decimal(5,4) DEFAULT NULL,
  `GoalsFor` mediumint(9) DEFAULT NULL,
  `GoalsAgainst` mediumint(9) DEFAULT NULL,
  `AverageGoalsFor` decimal(6,4) DEFAULT NULL,
  `AverageGoalsAgainst` decimal(6,4) DEFAULT NULL,
  `GoalRatio` decimal(7,4) DEFAULT NULL,
  `MostGoalsScored` tinyint(4) DEFAULT NULL,
  `LeastGoalsScored` tinyint(4) NOT NULL DEFAULT 50,
  `MostGoalsConceded` tinyint(4) DEFAULT NULL,
  `LeastGoalsConceded` tinyint(4) NOT NULL DEFAULT 50,
  `BiggestWinDifference` tinyint(4) DEFAULT NULL,
  `BiggestDrawSum` tinyint(4) DEFAULT NULL,
  `BiggestLossDifference` tinyint(4) DEFAULT NULL,
  `SmallestSumOfGoals` tinyint(4) NOT NULL DEFAULT 50,
  `BiggestSumOfGoals` tinyint(4) DEFAULT NULL,
  `DoubleDigits` mediumint(9) DEFAULT NULL,
  `CleanSheets` mediumint(9) DEFAULT NULL,
  `DoubleDigitsConceded` mediumint(9) DEFAULT NULL,
  `CleanSheetsConceded` mediumint(9) DEFAULT NULL,
  `DoubleDigitsRatio` decimal(5,4) DEFAULT NULL,
  `CleanSheetsRatio` decimal(5,4) DEFAULT NULL,
  `DoubleDigitsConcededRatio` decimal(5,4) DEFAULT NULL,
  `CleanSheetsConcededRatio` decimal(5,4) DEFAULT NULL,
  `DifferentOpponents` smallint(6) DEFAULT NULL,
  `DifferentVictims` smallint(6) DEFAULT NULL,
  `DoubleDigitsVictims` smallint(6) DEFAULT NULL,
  `CleanSheetsVictims` smallint(6) DEFAULT NULL,
  `MostGoalsConcededVictims` smallint(6) DEFAULT NULL,
  `LeastGoalsScoredVictims` smallint(6) DEFAULT NULL,
  `BiggestLossVictims` smallint(6) DEFAULT NULL,
  `DifferentCulprits` smallint(6) DEFAULT NULL,
  `DoubleDigitsCulprits` smallint(6) DEFAULT NULL,
  `CleanSheetsCulprits` smallint(6) DEFAULT NULL,
  `MostGoalsScoredCulprits` smallint(6) DEFAULT NULL,
  `LeastGoalsConcededCulprits` smallint(6) DEFAULT NULL,
  `BiggestWinCulprits` smallint(6) DEFAULT NULL,
  `SumOfOpponentsRating` decimal(15,6) DEFAULT NULL,
  `AverageOpponentRating` decimal(7,3) DEFAULT NULL,
  `HighestRatedVictim` decimal(6,2) DEFAULT NULL,
  `LowestRatedCulprit` decimal(6,2) NOT NULL DEFAULT 5000.00,
  `CurrentRatingAscent` decimal(14,6) DEFAULT NULL,
  `BiggestRatingAscent` decimal(14,6) DEFAULT NULL,
  `CurrentRatingDescent` decimal(14,6) DEFAULT NULL,
  `BiggestRatingDescent` decimal(14,6) DEFAULT NULL,
  `LowestRating` decimal(10,6) NOT NULL DEFAULT 5000.00,
  `PeakRating` decimal(10,6) DEFAULT NULL,
  `WinningStreak` mediumint(9) DEFAULT NULL,
  `DrawingStreak` mediumint(9) DEFAULT NULL,
  `LosingStreak` mediumint(9) DEFAULT NULL,
  `NonWinStreak` mediumint(9) DEFAULT NULL,
  `NonDrawStreak` mediumint(9) DEFAULT NULL,
  `NonLossStreak` mediumint(9) DEFAULT NULL,
  `LongestWinningStreak` mediumint(9) DEFAULT NULL,
  `LongestDrawingStreak` mediumint(9) DEFAULT NULL,
  `LongestLosingStreak` mediumint(9) DEFAULT NULL,
  `LongestNonWinStreak` mediumint(9) DEFAULT NULL,
  `LongestNonDrawStreak` mediumint(9) DEFAULT NULL,
  `LongestNonLossStreak` mediumint(9) DEFAULT NULL,
  `ScoreStreak` mediumint(9) NOT NULL DEFAULT 0,
  `MerchantStreak` mediumint(9) NOT NULL DEFAULT 0,
  `ExactTenGoalStreak` mediumint(9) NOT NULL DEFAULT 0,
  `WinMarginOneStreak` mediumint(9) NOT NULL DEFAULT 0,
  `LossMarginOneStreak` mediumint(9) NOT NULL DEFAULT 0,
  `LastGame` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `LastGameGameID` int(11) DEFAULT NULL,
  `LastWinGameID` int(11) DEFAULT NULL,
  `LastDrawGameID` int(11) DEFAULT NULL,
  `LastLossGameID` int(11) DEFAULT NULL,
  `LowestRatingGameID` int(11) DEFAULT NULL,
  `PeakRatingGameID` int(11) DEFAULT NULL,
  `MostGoalsScoredGameID` int(11) DEFAULT NULL,
  `LeastGoalsScoredGameID` int(11) DEFAULT NULL,
  `MostGoalsConcededGameID` int(11) DEFAULT NULL,
  `LeastGoalsConcededGameID` int(11) DEFAULT NULL,
  `BiggestWinGameID` int(11) DEFAULT NULL,
  `BiggestDrawGameID` int(11) DEFAULT NULL,
  `BiggestLossGameID` int(11) DEFAULT NULL,
  `SmallestSumOfGoalsGameID` int(11) DEFAULT NULL,
  `BiggestSumOfGoalsGameID` int(11) DEFAULT NULL,
  `MostGoalsScoredVictimID` int(11) DEFAULT NULL,
  `LeastGoalsConcededVictimID` int(11) DEFAULT NULL,
  `BiggestWinVictimID` int(11) DEFAULT NULL,
  `MostGoalsConcededCulpritID` int(11) DEFAULT NULL,
  `LeastGoalsScoredCulpritID` int(11) DEFAULT NULL,
  `BiggestLossCulpritID` int(11) DEFAULT NULL,
  `HighestRatedVictimGameID` int(11) DEFAULT NULL,
  `LowestRatedCulpritGameID` int(11) DEFAULT NULL,
  -- Honours cumulative (mirrors amiga_player_tournament_totals)
  `tournaments_played` int(11) NOT NULL DEFAULT 0,
  `tournaments_won` int(11) NOT NULL DEFAULT 0,
  `event_gold` int(11) NOT NULL DEFAULT 0,
  `event_silver` int(11) NOT NULL DEFAULT 0,
  `event_bronze` int(11) NOT NULL DEFAULT 0,
  `event_podiums` int(11) NOT NULL DEFAULT 0,
  `honours_last_event_date` date DEFAULT NULL,
  `honours_last_tournament_id` int(11) DEFAULT NULL,
  -- Running career extrema for LB parity
  `career_best_performance_rating` decimal(10,6) DEFAULT NULL,
  `career_best_performance_tournament_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`player_id`, `tournament_id`),
  KEY `idx_snapshots_player_chrono` (`player_id`, `event_date`, `event_chrono`, `tournament_id`),
  KEY `idx_snapshots_tournament_player` (`tournament_id`, `player_id`),
  KEY `idx_snapshots_rating_after` (`rating_after`),
  KEY `idx_snapshots_finalized_at` (`finalized_at`),
  CONSTRAINT `fk_snapshots_player`
    FOREIGN KEY (`player_id`) REFERENCES `amiga_players` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_snapshots_tournament`
    FOREIGN KEY (`tournament_id`) REFERENCES `tournaments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `amiga_player_current` (
  `player_id` int(11) NOT NULL,
  `last_tournament_id` int(11) DEFAULT NULL,
  `last_event_date` date DEFAULT NULL,
  `last_finalized_at` datetime DEFAULT NULL,
  -- Career cumulative (same columns as snapshot career block)
  `Display` mediumint(9) DEFAULT 0,
  `Rating` decimal(10,6) DEFAULT NULL,
  `NumberGames` mediumint(9) DEFAULT NULL,
  `NumberWins` mediumint(9) DEFAULT NULL,
  `NumberDraws` mediumint(9) DEFAULT NULL,
  `NumberLosses` mediumint(9) DEFAULT NULL,
  `WinRatio` decimal(5,4) DEFAULT NULL,
  `DrawRatio` decimal(5,4) DEFAULT NULL,
  `LossRatio` decimal(5,4) DEFAULT NULL,
  `GoalsFor` mediumint(9) DEFAULT NULL,
  `GoalsAgainst` mediumint(9) DEFAULT NULL,
  `AverageGoalsFor` decimal(6,4) DEFAULT NULL,
  `AverageGoalsAgainst` decimal(6,4) DEFAULT NULL,
  `GoalRatio` decimal(7,4) DEFAULT NULL,
  `MostGoalsScored` tinyint(4) DEFAULT NULL,
  `LeastGoalsScored` tinyint(4) NOT NULL DEFAULT 50,
  `MostGoalsConceded` tinyint(4) DEFAULT NULL,
  `LeastGoalsConceded` tinyint(4) NOT NULL DEFAULT 50,
  `BiggestWinDifference` tinyint(4) DEFAULT NULL,
  `BiggestDrawSum` tinyint(4) DEFAULT NULL,
  `BiggestLossDifference` tinyint(4) DEFAULT NULL,
  `SmallestSumOfGoals` tinyint(4) NOT NULL DEFAULT 50,
  `BiggestSumOfGoals` tinyint(4) DEFAULT NULL,
  `DoubleDigits` mediumint(9) DEFAULT NULL,
  `CleanSheets` mediumint(9) DEFAULT NULL,
  `DoubleDigitsConceded` mediumint(9) DEFAULT NULL,
  `CleanSheetsConceded` mediumint(9) DEFAULT NULL,
  `DoubleDigitsRatio` decimal(5,4) DEFAULT NULL,
  `CleanSheetsRatio` decimal(5,4) DEFAULT NULL,
  `DoubleDigitsConcededRatio` decimal(5,4) DEFAULT NULL,
  `CleanSheetsConcededRatio` decimal(5,4) DEFAULT NULL,
  `DifferentOpponents` smallint(6) DEFAULT NULL,
  `DifferentVictims` smallint(6) DEFAULT NULL,
  `DoubleDigitsVictims` smallint(6) DEFAULT NULL,
  `CleanSheetsVictims` smallint(6) DEFAULT NULL,
  `MostGoalsConcededVictims` smallint(6) DEFAULT NULL,
  `LeastGoalsScoredVictims` smallint(6) DEFAULT NULL,
  `BiggestLossVictims` smallint(6) DEFAULT NULL,
  `DifferentCulprits` smallint(6) DEFAULT NULL,
  `DoubleDigitsCulprits` smallint(6) DEFAULT NULL,
  `CleanSheetsCulprits` smallint(6) DEFAULT NULL,
  `MostGoalsScoredCulprits` smallint(6) DEFAULT NULL,
  `LeastGoalsConcededCulprits` smallint(6) DEFAULT NULL,
  `BiggestWinCulprits` smallint(6) DEFAULT NULL,
  `SumOfOpponentsRating` decimal(15,6) DEFAULT NULL,
  `AverageOpponentRating` decimal(7,3) DEFAULT NULL,
  `HighestRatedVictim` decimal(6,2) DEFAULT NULL,
  `LowestRatedCulprit` decimal(6,2) NOT NULL DEFAULT 5000.00,
  `CurrentRatingAscent` decimal(14,6) DEFAULT NULL,
  `BiggestRatingAscent` decimal(14,6) DEFAULT NULL,
  `CurrentRatingDescent` decimal(14,6) DEFAULT NULL,
  `BiggestRatingDescent` decimal(14,6) DEFAULT NULL,
  `LowestRating` decimal(10,6) NOT NULL DEFAULT 5000.00,
  `PeakRating` decimal(10,6) DEFAULT NULL,
  `WinningStreak` mediumint(9) DEFAULT NULL,
  `DrawingStreak` mediumint(9) DEFAULT NULL,
  `LosingStreak` mediumint(9) DEFAULT NULL,
  `NonWinStreak` mediumint(9) DEFAULT NULL,
  `NonDrawStreak` mediumint(9) DEFAULT NULL,
  `NonLossStreak` mediumint(9) DEFAULT NULL,
  `LongestWinningStreak` mediumint(9) DEFAULT NULL,
  `LongestDrawingStreak` mediumint(9) DEFAULT NULL,
  `LongestLosingStreak` mediumint(9) DEFAULT NULL,
  `LongestNonWinStreak` mediumint(9) DEFAULT NULL,
  `LongestNonDrawStreak` mediumint(9) DEFAULT NULL,
  `LongestNonLossStreak` mediumint(9) DEFAULT NULL,
  `ScoreStreak` mediumint(9) NOT NULL DEFAULT 0,
  `MerchantStreak` mediumint(9) NOT NULL DEFAULT 0,
  `ExactTenGoalStreak` mediumint(9) NOT NULL DEFAULT 0,
  `WinMarginOneStreak` mediumint(9) NOT NULL DEFAULT 0,
  `LossMarginOneStreak` mediumint(9) NOT NULL DEFAULT 0,
  `LastGame` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `LastGameGameID` int(11) DEFAULT NULL,
  `LastWinGameID` int(11) DEFAULT NULL,
  `LastDrawGameID` int(11) DEFAULT NULL,
  `LastLossGameID` int(11) DEFAULT NULL,
  `LowestRatingGameID` int(11) DEFAULT NULL,
  `PeakRatingGameID` int(11) DEFAULT NULL,
  `MostGoalsScoredGameID` int(11) DEFAULT NULL,
  `LeastGoalsScoredGameID` int(11) DEFAULT NULL,
  `MostGoalsConcededGameID` int(11) DEFAULT NULL,
  `LeastGoalsConcededGameID` int(11) DEFAULT NULL,
  `BiggestWinGameID` int(11) DEFAULT NULL,
  `BiggestDrawGameID` int(11) DEFAULT NULL,
  `BiggestLossGameID` int(11) DEFAULT NULL,
  `SmallestSumOfGoalsGameID` int(11) DEFAULT NULL,
  `BiggestSumOfGoalsGameID` int(11) DEFAULT NULL,
  `MostGoalsScoredVictimID` int(11) DEFAULT NULL,
  `LeastGoalsConcededVictimID` int(11) DEFAULT NULL,
  `BiggestWinVictimID` int(11) DEFAULT NULL,
  `MostGoalsConcededCulpritID` int(11) DEFAULT NULL,
  `LeastGoalsScoredCulpritID` int(11) DEFAULT NULL,
  `BiggestLossCulpritID` int(11) DEFAULT NULL,
  `HighestRatedVictimGameID` int(11) DEFAULT NULL,
  `LowestRatedCulpritGameID` int(11) DEFAULT NULL,
  -- Honours cumulative
  `tournaments_played` int(11) NOT NULL DEFAULT 0,
  `tournaments_won` int(11) NOT NULL DEFAULT 0,
  `event_gold` int(11) NOT NULL DEFAULT 0,
  `event_silver` int(11) NOT NULL DEFAULT 0,
  `event_bronze` int(11) NOT NULL DEFAULT 0,
  `event_podiums` int(11) NOT NULL DEFAULT 0,
  `career_best_performance_rating` decimal(10,6) DEFAULT NULL,
  `career_best_performance_tournament_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`player_id`),
  KEY `idx_player_current_rating` (`Rating`),
  KEY `idx_player_current_number_games` (`NumberGames`),
  KEY `idx_player_current_last_tournament` (`last_tournament_id`),
  CONSTRAINT `fk_player_current_player`
    FOREIGN KEY (`player_id`) REFERENCES `amiga_players` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
