-- Per–World Cup event stats (one row per WC tournament_id).
-- Spec: docs/amiga-world-cup-stats-table-plan.md

SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS `amiga_world_cup_stats` (
  `tournament_id` int(11) NOT NULL,
  `tournament_name` varchar(50) NOT NULL,
  `calendar_year` int(11) DEFAULT NULL,
  `event_date` date DEFAULT NULL,
  `event_chrono` double DEFAULT NULL,
  `host_country` varchar(64) DEFAULT NULL,
  `host_city` varchar(64) DEFAULT NULL,
  `rated_games` int(11) NOT NULL DEFAULT 0,
  `decided_games` int(11) NOT NULL DEFAULT 0,
  `draws` int(11) NOT NULL DEFAULT 0,
  `goals` int(11) NOT NULL DEFAULT 0,
  `double_digit_slots` int(11) NOT NULL DEFAULT 0,
  `clean_sheet_slots` int(11) NOT NULL DEFAULT 0,
  `high_scoring_games` int(11) NOT NULL DEFAULT 0,
  `low_scoring_games` int(11) NOT NULL DEFAULT 0,
  `blowout_games` int(11) NOT NULL DEFAULT 0,
  `knockout_games` int(11) NOT NULL DEFAULT 0,
  `group_games` int(11) NOT NULL DEFAULT 0,
  `goals_per_game` decimal(12,7) DEFAULT NULL,
  `draw_rate` decimal(10,8) DEFAULT NULL,
  `decided_rate` decimal(10,8) DEFAULT NULL,
  `double_digit_rate` decimal(10,8) DEFAULT NULL,
  `clean_sheet_rate` decimal(10,8) DEFAULT NULL,
  `high_scoring_rate` decimal(10,8) DEFAULT NULL,
  `low_scoring_rate` decimal(10,8) DEFAULT NULL,
  `blowout_rate` decimal(10,8) DEFAULT NULL,
  `distinct_players` int(11) NOT NULL DEFAULT 0,
  `distinct_player_nationalities` int(11) NOT NULL DEFAULT 0,
  `max_games_one_player` int(11) NOT NULL DEFAULT 0,
  `first_time_wc_players` int(11) NOT NULL DEFAULT 0,
  `distinct_opponent_pairs` int(11) NOT NULL DEFAULT 0,
  `avg_games_per_player` decimal(10,3) DEFAULT NULL,
  `avg_opponents_per_player` decimal(10,3) DEFAULT NULL,
  `distinct_host_country_players` int(11) NOT NULL DEFAULT 0,
  `distinct_guest_players` int(11) NOT NULL DEFAULT 0,
  `guest_player_share` decimal(10,8) DEFAULT NULL,
  `distinct_opponent_countries_pairs` int(11) NOT NULL DEFAULT 0,
  `international_games` int(11) NOT NULL DEFAULT 0,
  `international_game_share` decimal(10,8) DEFAULT NULL,
  `highest_goal_sum` int(11) DEFAULT NULL,
  `highest_goal_sum_game_id` int(11) DEFAULT NULL,
  `lowest_goal_sum` int(11) DEFAULT NULL,
  `lowest_goal_sum_game_id` int(11) DEFAULT NULL,
  `biggest_margin` int(11) DEFAULT NULL,
  `biggest_margin_game_id` int(11) DEFAULT NULL,
  `highest_scoring_draw_sum` int(11) DEFAULT NULL,
  `highest_scoring_draw_game_id` int(11) DEFAULT NULL,
  `most_goals_one_player_game` int(11) DEFAULT NULL,
  `most_goals_one_player_game_id` int(11) DEFAULT NULL,
  `gold_player_id` int(11) DEFAULT NULL,
  `silver_player_id` int(11) DEFAULT NULL,
  `bronze_player_id` int(11) DEFAULT NULL,
  `champion_game_count` int(11) DEFAULT NULL,
  `share_of_year_games` decimal(10,8) DEFAULT NULL,
  `finalized_at` datetime NOT NULL,
  PRIMARY KEY (`tournament_id`),
  KEY `idx_wc_stats_year` (`calendar_year`, `event_date`, `tournament_id`),
  CONSTRAINT `fk_wc_stats_tournament`
    FOREIGN KEY (`tournament_id`) REFERENCES `tournaments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
