-- World Cup country slice tables (nation × WC career).
-- Policy: docs/amiga-world-cups-country-slice-policy.md

SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS `amiga_country_slice_totals` (
  `country_token` varchar(128) NOT NULL,
  `slice_key` varchar(32) NOT NULL,
  `players` smallint(6) NOT NULL DEFAULT 0,
  `wc_participations` mediumint(9) NOT NULL DEFAULT 0,
  `wc_participations_per_player` decimal(8,4) DEFAULT NULL,
  `games_per_player` decimal(8,4) DEFAULT NULL,
  `domestic_games` mediumint(9) NOT NULL DEFAULT 0,
  `domestic_game_share` decimal(8,6) DEFAULT NULL,
  `international_games` mediumint(9) NOT NULL DEFAULT 0,
  `international_game_share` decimal(8,6) DEFAULT NULL,
  `games_share` decimal(8,6) DEFAULT NULL,
  `goals_share` decimal(8,6) DEFAULT NULL,
  `realm_wc_tournament_count` smallint(6) NOT NULL DEFAULT 0,
  `realm_wc_player_games` mediumint(9) NOT NULL DEFAULT 0,
  `realm_wc_goals_for` mediumint(9) NOT NULL DEFAULT 0,
  `tournaments_with_nation` smallint(6) NOT NULL DEFAULT 0,
  `gold` smallint(6) NOT NULL DEFAULT 0,
  `silver` smallint(6) NOT NULL DEFAULT 0,
  `bronze` smallint(6) NOT NULL DEFAULT 0,
  `podiums` smallint(6) NOT NULL DEFAULT 0,
  `games` mediumint(9) NOT NULL DEFAULT 0,
  `wins` mediumint(9) NOT NULL DEFAULT 0,
  `draws` mediumint(9) NOT NULL DEFAULT 0,
  `losses` mediumint(9) NOT NULL DEFAULT 0,
  `points` mediumint(9) NOT NULL DEFAULT 0,
  `points_per_realm_wc` decimal(8,4) DEFAULT NULL,
  `win_rate` decimal(8,6) DEFAULT NULL,
  `average_opponent_rating` decimal(10,4) DEFAULT NULL,
  `performance_rating` decimal(10,4) DEFAULT NULL,
  `goals_for` mediumint(9) NOT NULL DEFAULT 0,
  `goals_against` mediumint(9) NOT NULL DEFAULT 0,
  `goal_ratio` decimal(10,8) DEFAULT NULL,
  `most_goals_scored` tinyint(4) NOT NULL DEFAULT 0,
  `most_goals_conceded` tinyint(4) NOT NULL DEFAULT 0,
  `biggest_win_difference` tinyint(4) NOT NULL DEFAULT 0,
  `biggest_loss_difference` tinyint(4) NOT NULL DEFAULT 0,
  `biggest_sum_of_goals` tinyint(4) NOT NULL DEFAULT 0,
  `biggest_draw_sum` tinyint(4) NOT NULL DEFAULT 0,
  `double_digits` mediumint(9) NOT NULL DEFAULT 0,
  `clean_sheets` mediumint(9) NOT NULL DEFAULT 0,
  `double_digits_ratio` decimal(5,4) DEFAULT NULL,
  `clean_sheets_ratio` decimal(5,4) DEFAULT NULL,
  `double_digits_conceded` mediumint(9) NOT NULL DEFAULT 0,
  `clean_sheets_conceded` mediumint(9) NOT NULL DEFAULT 0,
  `double_digits_conceded_ratio` decimal(5,4) DEFAULT NULL,
  `clean_sheets_conceded_ratio` decimal(5,4) DEFAULT NULL,
  `opponent_countries_faced` smallint(5) unsigned NOT NULL DEFAULT 0,
  `opponent_countries_beaten` smallint(5) unsigned NOT NULL DEFAULT 0,
  `different_opponents` smallint(6) NOT NULL DEFAULT 0,
  `different_victims` smallint(6) NOT NULL DEFAULT 0,
  `double_digits_victims` smallint(6) NOT NULL DEFAULT 0,
  `clean_sheets_victims` smallint(6) NOT NULL DEFAULT 0,
  PRIMARY KEY (`country_token`, `slice_key`),
  KEY `idx_country_slice_totals_key_gold` (`slice_key`, `gold`),
  KEY `idx_country_slice_totals_key_points` (`slice_key`, `points`),
  KEY `idx_country_slice_totals_key_games` (`slice_key`, `games`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `amiga_country_slice_at_event` (
  `country_token` varchar(128) NOT NULL,
  `slice_key` varchar(32) NOT NULL,
  `as_of_tournament_id` int(11) NOT NULL,
  `event_date` date DEFAULT NULL,
  `event_chrono` double DEFAULT NULL,
  `players` smallint(6) NOT NULL DEFAULT 0,
  `wc_participations` mediumint(9) NOT NULL DEFAULT 0,
  `wc_participations_per_player` decimal(8,4) DEFAULT NULL,
  `games_per_player` decimal(8,4) DEFAULT NULL,
  `domestic_games` mediumint(9) NOT NULL DEFAULT 0,
  `domestic_game_share` decimal(8,6) DEFAULT NULL,
  `international_games` mediumint(9) NOT NULL DEFAULT 0,
  `international_game_share` decimal(8,6) DEFAULT NULL,
  `games_share` decimal(8,6) DEFAULT NULL,
  `goals_share` decimal(8,6) DEFAULT NULL,
  `realm_wc_tournament_count` smallint(6) NOT NULL DEFAULT 0,
  `realm_wc_player_games` mediumint(9) NOT NULL DEFAULT 0,
  `realm_wc_goals_for` mediumint(9) NOT NULL DEFAULT 0,
  `tournaments_with_nation` smallint(6) NOT NULL DEFAULT 0,
  `gold` smallint(6) NOT NULL DEFAULT 0,
  `silver` smallint(6) NOT NULL DEFAULT 0,
  `bronze` smallint(6) NOT NULL DEFAULT 0,
  `podiums` smallint(6) NOT NULL DEFAULT 0,
  `games` mediumint(9) NOT NULL DEFAULT 0,
  `wins` mediumint(9) NOT NULL DEFAULT 0,
  `draws` mediumint(9) NOT NULL DEFAULT 0,
  `losses` mediumint(9) NOT NULL DEFAULT 0,
  `points` mediumint(9) NOT NULL DEFAULT 0,
  `points_per_realm_wc` decimal(8,4) DEFAULT NULL,
  `win_rate` decimal(8,6) DEFAULT NULL,
  `average_opponent_rating` decimal(10,4) DEFAULT NULL,
  `performance_rating` decimal(10,4) DEFAULT NULL,
  `goals_for` mediumint(9) NOT NULL DEFAULT 0,
  `goals_against` mediumint(9) NOT NULL DEFAULT 0,
  `goal_ratio` decimal(10,8) DEFAULT NULL,
  `most_goals_scored` tinyint(4) NOT NULL DEFAULT 0,
  `most_goals_conceded` tinyint(4) NOT NULL DEFAULT 0,
  `biggest_win_difference` tinyint(4) NOT NULL DEFAULT 0,
  `biggest_loss_difference` tinyint(4) NOT NULL DEFAULT 0,
  `biggest_sum_of_goals` tinyint(4) NOT NULL DEFAULT 0,
  `biggest_draw_sum` tinyint(4) NOT NULL DEFAULT 0,
  `double_digits` mediumint(9) NOT NULL DEFAULT 0,
  `clean_sheets` mediumint(9) NOT NULL DEFAULT 0,
  `double_digits_ratio` decimal(5,4) DEFAULT NULL,
  `clean_sheets_ratio` decimal(5,4) DEFAULT NULL,
  `double_digits_conceded` mediumint(9) NOT NULL DEFAULT 0,
  `clean_sheets_conceded` mediumint(9) NOT NULL DEFAULT 0,
  `double_digits_conceded_ratio` decimal(5,4) DEFAULT NULL,
  `clean_sheets_conceded_ratio` decimal(5,4) DEFAULT NULL,
  `opponent_countries_faced` smallint(5) unsigned NOT NULL DEFAULT 0,
  `opponent_countries_beaten` smallint(5) unsigned NOT NULL DEFAULT 0,
  `different_opponents` smallint(6) NOT NULL DEFAULT 0,
  `different_victims` smallint(6) NOT NULL DEFAULT 0,
  `double_digits_victims` smallint(6) NOT NULL DEFAULT 0,
  `clean_sheets_victims` smallint(6) NOT NULL DEFAULT 0,
  PRIMARY KEY (`country_token`, `slice_key`, `as_of_tournament_id`),
  KEY `idx_country_slice_at_event_tournament` (`as_of_tournament_id`),
  CONSTRAINT `fk_country_slice_at_event_tournament`
    FOREIGN KEY (`as_of_tournament_id`) REFERENCES `tournaments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
