-- World Cup Hall of Fame store (sparse, WC-finalize only) + slice extensions.
-- Policy: docs/amiga-wc-hof-policy.md  Plan: docs/amiga-wc-hof-implementation-plan.md (SCH-046)
-- Manifest: scripts/amiga/wc_hof_columns.py  (28 record groups, 122 payload columns)
-- Apply after 045: fresh bundle via schema_bundles DERIVED_SQL.

SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS `amiga_wc_hof_snapshots` (
  `tournament_id` int(11) NOT NULL,
  `event_date` date DEFAULT NULL,
  `event_chrono` double DEFAULT NULL,
  `tournament_name` varchar(50) NOT NULL,
  `finalized_at` datetime NOT NULL,
  `MostWcPlayed` int(11) DEFAULT NULL,
  `MostWcGold` int(11) DEFAULT NULL,
  `MostWcGames` int(11) DEFAULT NULL,
  `MostWcWins` int(11) DEFAULT NULL,
  `MostWcPoints` int(11) DEFAULT NULL,
  `BestWcPtsPerGame` decimal(6,4) DEFAULT NULL,
  `BestWcWinRate` decimal(5,4) DEFAULT NULL,
  `MostWcGoalsFor` int(11) DEFAULT NULL,
  `BestWcGoalsForPerGame` decimal(6,4) DEFAULT NULL,
  `BestWcGoalsAgainstPerGame` decimal(6,4) DEFAULT NULL,
  `BestWcGoalDiffPerGame` decimal(7,4) DEFAULT NULL,
  `BestWcGoalRatio` decimal(7,4) DEFAULT NULL,
  `MostWcDoubleDigits` int(11) DEFAULT NULL,
  `BestWcDoubleDigitsRatio` decimal(5,4) DEFAULT NULL,
  `MostWcCleanSheets` int(11) DEFAULT NULL,
  `BestWcCleanSheetsRatio` decimal(5,4) DEFAULT NULL,
  `MostWcOpponents` int(11) DEFAULT NULL,
  `MostWcVictims` int(11) DEFAULT NULL,
  `MostWcDoubleDigitsVictims` int(11) DEFAULT NULL,
  `MostWcCleanSheetsVictims` int(11) DEFAULT NULL,
  `MostWcGoalsInOneGame` int(11) DEFAULT NULL,
  `BiggestWcWinDifference` int(11) DEFAULT NULL,
  `BiggestWcDrawSum` int(11) DEFAULT NULL,
  `BiggestWcSumOfGoals` int(11) DEFAULT NULL,
  `MostWcBestAttackAwards` int(11) DEFAULT NULL,
  `MostWcBestDefenseAwards` int(11) DEFAULT NULL,
  `BestSingleWcGoalsForPerGame` decimal(6,4) DEFAULT NULL,
  `BestSingleWcGoalsAgainstPerGame` decimal(6,4) DEFAULT NULL,
  `MostWcPlayedID` int(11) DEFAULT NULL,
  `MostWcGoldID` int(11) DEFAULT NULL,
  `MostWcGamesID` int(11) DEFAULT NULL,
  `MostWcWinsID` int(11) DEFAULT NULL,
  `MostWcPointsID` int(11) DEFAULT NULL,
  `BestWcPtsPerGameID` int(11) DEFAULT NULL,
  `BestWcWinRateID` int(11) DEFAULT NULL,
  `MostWcGoalsForID` int(11) DEFAULT NULL,
  `BestWcGoalsForPerGameID` int(11) DEFAULT NULL,
  `BestWcGoalsAgainstPerGameID` int(11) DEFAULT NULL,
  `BestWcGoalDiffPerGameID` int(11) DEFAULT NULL,
  `BestWcGoalRatioID` int(11) DEFAULT NULL,
  `MostWcDoubleDigitsID` int(11) DEFAULT NULL,
  `BestWcDoubleDigitsRatioID` int(11) DEFAULT NULL,
  `MostWcCleanSheetsID` int(11) DEFAULT NULL,
  `BestWcCleanSheetsRatioID` int(11) DEFAULT NULL,
  `MostWcOpponentsID` int(11) DEFAULT NULL,
  `MostWcVictimsID` int(11) DEFAULT NULL,
  `MostWcDoubleDigitsVictimsID` int(11) DEFAULT NULL,
  `MostWcCleanSheetsVictimsID` int(11) DEFAULT NULL,
  `MostWcGoalsInOneGameID` int(11) DEFAULT NULL,
  `BiggestWcWinDifferenceID` int(11) DEFAULT NULL,
  `BiggestWcDrawSumIDA` int(11) DEFAULT NULL,
  `BiggestWcDrawSumIDB` int(11) DEFAULT NULL,
  `BiggestWcSumOfGoalsIDA` int(11) DEFAULT NULL,
  `BiggestWcSumOfGoalsIDB` int(11) DEFAULT NULL,
  `MostWcBestAttackAwardsID` int(11) DEFAULT NULL,
  `MostWcBestDefenseAwardsID` int(11) DEFAULT NULL,
  `BestSingleWcGoalsForPerGameID` int(11) DEFAULT NULL,
  `BestSingleWcGoalsAgainstPerGameID` int(11) DEFAULT NULL,
  `MostWcPlayedName` varchar(50) DEFAULT NULL,
  `MostWcGoldName` varchar(50) DEFAULT NULL,
  `MostWcGamesName` varchar(50) DEFAULT NULL,
  `MostWcWinsName` varchar(50) DEFAULT NULL,
  `MostWcPointsName` varchar(50) DEFAULT NULL,
  `BestWcPtsPerGameName` varchar(50) DEFAULT NULL,
  `BestWcWinRateName` varchar(50) DEFAULT NULL,
  `MostWcGoalsForName` varchar(50) DEFAULT NULL,
  `BestWcGoalsForPerGameName` varchar(50) DEFAULT NULL,
  `BestWcGoalsAgainstPerGameName` varchar(50) DEFAULT NULL,
  `BestWcGoalDiffPerGameName` varchar(50) DEFAULT NULL,
  `BestWcGoalRatioName` varchar(50) DEFAULT NULL,
  `MostWcDoubleDigitsName` varchar(50) DEFAULT NULL,
  `BestWcDoubleDigitsRatioName` varchar(50) DEFAULT NULL,
  `MostWcCleanSheetsName` varchar(50) DEFAULT NULL,
  `BestWcCleanSheetsRatioName` varchar(50) DEFAULT NULL,
  `MostWcOpponentsName` varchar(50) DEFAULT NULL,
  `MostWcVictimsName` varchar(50) DEFAULT NULL,
  `MostWcDoubleDigitsVictimsName` varchar(50) DEFAULT NULL,
  `MostWcCleanSheetsVictimsName` varchar(50) DEFAULT NULL,
  `MostWcGoalsInOneGameName` varchar(50) DEFAULT NULL,
  `BiggestWcWinDifferenceName` varchar(50) DEFAULT NULL,
  `BiggestWcDrawSumNameA` varchar(50) DEFAULT NULL,
  `BiggestWcDrawSumNameB` varchar(50) DEFAULT NULL,
  `BiggestWcSumOfGoalsNameA` varchar(50) DEFAULT NULL,
  `BiggestWcSumOfGoalsNameB` varchar(50) DEFAULT NULL,
  `MostWcBestAttackAwardsName` varchar(50) DEFAULT NULL,
  `MostWcBestDefenseAwardsName` varchar(50) DEFAULT NULL,
  `BestSingleWcGoalsForPerGameName` varchar(50) DEFAULT NULL,
  `BestSingleWcGoalsAgainstPerGameName` varchar(50) DEFAULT NULL,
  `MostWcPlayedDate` date DEFAULT NULL,
  `MostWcGoldDate` date DEFAULT NULL,
  `MostWcGamesDate` date DEFAULT NULL,
  `MostWcWinsDate` date DEFAULT NULL,
  `MostWcPointsDate` date DEFAULT NULL,
  `BestWcPtsPerGameDate` date DEFAULT NULL,
  `BestWcWinRateDate` date DEFAULT NULL,
  `MostWcGoalsForDate` date DEFAULT NULL,
  `BestWcGoalsForPerGameDate` date DEFAULT NULL,
  `BestWcGoalsAgainstPerGameDate` date DEFAULT NULL,
  `BestWcGoalDiffPerGameDate` date DEFAULT NULL,
  `BestWcGoalRatioDate` date DEFAULT NULL,
  `MostWcDoubleDigitsDate` date DEFAULT NULL,
  `BestWcDoubleDigitsRatioDate` date DEFAULT NULL,
  `MostWcCleanSheetsDate` date DEFAULT NULL,
  `BestWcCleanSheetsRatioDate` date DEFAULT NULL,
  `MostWcOpponentsDate` date DEFAULT NULL,
  `MostWcVictimsDate` date DEFAULT NULL,
  `MostWcDoubleDigitsVictimsDate` date DEFAULT NULL,
  `MostWcCleanSheetsVictimsDate` date DEFAULT NULL,
  `MostWcGoalsInOneGameDate` date DEFAULT NULL,
  `BiggestWcWinDifferenceDate` date DEFAULT NULL,
  `BiggestWcDrawSumDate` date DEFAULT NULL,
  `BiggestWcSumOfGoalsDate` date DEFAULT NULL,
  `MostWcBestAttackAwardsDate` date DEFAULT NULL,
  `MostWcBestDefenseAwardsDate` date DEFAULT NULL,
  `BestSingleWcGoalsForPerGameDate` date DEFAULT NULL,
  `BestSingleWcGoalsAgainstPerGameDate` date DEFAULT NULL,
  `MostWcGoalsInOneGameGameID` int(11) DEFAULT NULL,
  `BiggestWcWinDifferenceGameID` int(11) DEFAULT NULL,
  `BiggestWcDrawSumGameID` int(11) DEFAULT NULL,
  `BiggestWcSumOfGoalsGameID` int(11) DEFAULT NULL,
  `BestSingleWcGoalsForPerGameTournamentID` int(11) DEFAULT NULL,
  `BestSingleWcGoalsAgainstPerGameTournamentID` int(11) DEFAULT NULL,
  PRIMARY KEY (`tournament_id`),
  KEY `idx_wc_hof_snapshots_chrono` (`event_date`, `event_chrono`, `tournament_id`),
  CONSTRAINT `fk_wc_hof_snapshots_tournament`
    FOREIGN KEY (`tournament_id`) REFERENCES `tournaments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `amiga_wc_hof_present` (
  `id` tinyint(4) NOT NULL,
  `MostWcPlayed` int(11) DEFAULT NULL,
  `MostWcGold` int(11) DEFAULT NULL,
  `MostWcGames` int(11) DEFAULT NULL,
  `MostWcWins` int(11) DEFAULT NULL,
  `MostWcPoints` int(11) DEFAULT NULL,
  `BestWcPtsPerGame` decimal(6,4) DEFAULT NULL,
  `BestWcWinRate` decimal(5,4) DEFAULT NULL,
  `MostWcGoalsFor` int(11) DEFAULT NULL,
  `BestWcGoalsForPerGame` decimal(6,4) DEFAULT NULL,
  `BestWcGoalsAgainstPerGame` decimal(6,4) DEFAULT NULL,
  `BestWcGoalDiffPerGame` decimal(7,4) DEFAULT NULL,
  `BestWcGoalRatio` decimal(7,4) DEFAULT NULL,
  `MostWcDoubleDigits` int(11) DEFAULT NULL,
  `BestWcDoubleDigitsRatio` decimal(5,4) DEFAULT NULL,
  `MostWcCleanSheets` int(11) DEFAULT NULL,
  `BestWcCleanSheetsRatio` decimal(5,4) DEFAULT NULL,
  `MostWcOpponents` int(11) DEFAULT NULL,
  `MostWcVictims` int(11) DEFAULT NULL,
  `MostWcDoubleDigitsVictims` int(11) DEFAULT NULL,
  `MostWcCleanSheetsVictims` int(11) DEFAULT NULL,
  `MostWcGoalsInOneGame` int(11) DEFAULT NULL,
  `BiggestWcWinDifference` int(11) DEFAULT NULL,
  `BiggestWcDrawSum` int(11) DEFAULT NULL,
  `BiggestWcSumOfGoals` int(11) DEFAULT NULL,
  `MostWcBestAttackAwards` int(11) DEFAULT NULL,
  `MostWcBestDefenseAwards` int(11) DEFAULT NULL,
  `BestSingleWcGoalsForPerGame` decimal(6,4) DEFAULT NULL,
  `BestSingleWcGoalsAgainstPerGame` decimal(6,4) DEFAULT NULL,
  `MostWcPlayedID` int(11) DEFAULT NULL,
  `MostWcGoldID` int(11) DEFAULT NULL,
  `MostWcGamesID` int(11) DEFAULT NULL,
  `MostWcWinsID` int(11) DEFAULT NULL,
  `MostWcPointsID` int(11) DEFAULT NULL,
  `BestWcPtsPerGameID` int(11) DEFAULT NULL,
  `BestWcWinRateID` int(11) DEFAULT NULL,
  `MostWcGoalsForID` int(11) DEFAULT NULL,
  `BestWcGoalsForPerGameID` int(11) DEFAULT NULL,
  `BestWcGoalsAgainstPerGameID` int(11) DEFAULT NULL,
  `BestWcGoalDiffPerGameID` int(11) DEFAULT NULL,
  `BestWcGoalRatioID` int(11) DEFAULT NULL,
  `MostWcDoubleDigitsID` int(11) DEFAULT NULL,
  `BestWcDoubleDigitsRatioID` int(11) DEFAULT NULL,
  `MostWcCleanSheetsID` int(11) DEFAULT NULL,
  `BestWcCleanSheetsRatioID` int(11) DEFAULT NULL,
  `MostWcOpponentsID` int(11) DEFAULT NULL,
  `MostWcVictimsID` int(11) DEFAULT NULL,
  `MostWcDoubleDigitsVictimsID` int(11) DEFAULT NULL,
  `MostWcCleanSheetsVictimsID` int(11) DEFAULT NULL,
  `MostWcGoalsInOneGameID` int(11) DEFAULT NULL,
  `BiggestWcWinDifferenceID` int(11) DEFAULT NULL,
  `BiggestWcDrawSumIDA` int(11) DEFAULT NULL,
  `BiggestWcDrawSumIDB` int(11) DEFAULT NULL,
  `BiggestWcSumOfGoalsIDA` int(11) DEFAULT NULL,
  `BiggestWcSumOfGoalsIDB` int(11) DEFAULT NULL,
  `MostWcBestAttackAwardsID` int(11) DEFAULT NULL,
  `MostWcBestDefenseAwardsID` int(11) DEFAULT NULL,
  `BestSingleWcGoalsForPerGameID` int(11) DEFAULT NULL,
  `BestSingleWcGoalsAgainstPerGameID` int(11) DEFAULT NULL,
  `MostWcPlayedName` varchar(50) DEFAULT NULL,
  `MostWcGoldName` varchar(50) DEFAULT NULL,
  `MostWcGamesName` varchar(50) DEFAULT NULL,
  `MostWcWinsName` varchar(50) DEFAULT NULL,
  `MostWcPointsName` varchar(50) DEFAULT NULL,
  `BestWcPtsPerGameName` varchar(50) DEFAULT NULL,
  `BestWcWinRateName` varchar(50) DEFAULT NULL,
  `MostWcGoalsForName` varchar(50) DEFAULT NULL,
  `BestWcGoalsForPerGameName` varchar(50) DEFAULT NULL,
  `BestWcGoalsAgainstPerGameName` varchar(50) DEFAULT NULL,
  `BestWcGoalDiffPerGameName` varchar(50) DEFAULT NULL,
  `BestWcGoalRatioName` varchar(50) DEFAULT NULL,
  `MostWcDoubleDigitsName` varchar(50) DEFAULT NULL,
  `BestWcDoubleDigitsRatioName` varchar(50) DEFAULT NULL,
  `MostWcCleanSheetsName` varchar(50) DEFAULT NULL,
  `BestWcCleanSheetsRatioName` varchar(50) DEFAULT NULL,
  `MostWcOpponentsName` varchar(50) DEFAULT NULL,
  `MostWcVictimsName` varchar(50) DEFAULT NULL,
  `MostWcDoubleDigitsVictimsName` varchar(50) DEFAULT NULL,
  `MostWcCleanSheetsVictimsName` varchar(50) DEFAULT NULL,
  `MostWcGoalsInOneGameName` varchar(50) DEFAULT NULL,
  `BiggestWcWinDifferenceName` varchar(50) DEFAULT NULL,
  `BiggestWcDrawSumNameA` varchar(50) DEFAULT NULL,
  `BiggestWcDrawSumNameB` varchar(50) DEFAULT NULL,
  `BiggestWcSumOfGoalsNameA` varchar(50) DEFAULT NULL,
  `BiggestWcSumOfGoalsNameB` varchar(50) DEFAULT NULL,
  `MostWcBestAttackAwardsName` varchar(50) DEFAULT NULL,
  `MostWcBestDefenseAwardsName` varchar(50) DEFAULT NULL,
  `BestSingleWcGoalsForPerGameName` varchar(50) DEFAULT NULL,
  `BestSingleWcGoalsAgainstPerGameName` varchar(50) DEFAULT NULL,
  `MostWcPlayedDate` date DEFAULT NULL,
  `MostWcGoldDate` date DEFAULT NULL,
  `MostWcGamesDate` date DEFAULT NULL,
  `MostWcWinsDate` date DEFAULT NULL,
  `MostWcPointsDate` date DEFAULT NULL,
  `BestWcPtsPerGameDate` date DEFAULT NULL,
  `BestWcWinRateDate` date DEFAULT NULL,
  `MostWcGoalsForDate` date DEFAULT NULL,
  `BestWcGoalsForPerGameDate` date DEFAULT NULL,
  `BestWcGoalsAgainstPerGameDate` date DEFAULT NULL,
  `BestWcGoalDiffPerGameDate` date DEFAULT NULL,
  `BestWcGoalRatioDate` date DEFAULT NULL,
  `MostWcDoubleDigitsDate` date DEFAULT NULL,
  `BestWcDoubleDigitsRatioDate` date DEFAULT NULL,
  `MostWcCleanSheetsDate` date DEFAULT NULL,
  `BestWcCleanSheetsRatioDate` date DEFAULT NULL,
  `MostWcOpponentsDate` date DEFAULT NULL,
  `MostWcVictimsDate` date DEFAULT NULL,
  `MostWcDoubleDigitsVictimsDate` date DEFAULT NULL,
  `MostWcCleanSheetsVictimsDate` date DEFAULT NULL,
  `MostWcGoalsInOneGameDate` date DEFAULT NULL,
  `BiggestWcWinDifferenceDate` date DEFAULT NULL,
  `BiggestWcDrawSumDate` date DEFAULT NULL,
  `BiggestWcSumOfGoalsDate` date DEFAULT NULL,
  `MostWcBestAttackAwardsDate` date DEFAULT NULL,
  `MostWcBestDefenseAwardsDate` date DEFAULT NULL,
  `BestSingleWcGoalsForPerGameDate` date DEFAULT NULL,
  `BestSingleWcGoalsAgainstPerGameDate` date DEFAULT NULL,
  `MostWcGoalsInOneGameGameID` int(11) DEFAULT NULL,
  `BiggestWcWinDifferenceGameID` int(11) DEFAULT NULL,
  `BiggestWcDrawSumGameID` int(11) DEFAULT NULL,
  `BiggestWcSumOfGoalsGameID` int(11) DEFAULT NULL,
  `BestSingleWcGoalsForPerGameTournamentID` int(11) DEFAULT NULL,
  `BestSingleWcGoalsAgainstPerGameTournamentID` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `amiga_player_slice_totals`
  ADD COLUMN `best_attack_awards` int(11) NOT NULL DEFAULT 0 AFTER `clean_sheets_victims`,
  ADD COLUMN `best_defense_awards` int(11) NOT NULL DEFAULT 0 AFTER `best_attack_awards`,
  ADD COLUMN `best_single_wc_gf_per_game` decimal(6,4) DEFAULT NULL AFTER `best_defense_awards`,
  ADD COLUMN `best_single_wc_gf_per_game_tournament_id` int(11) DEFAULT NULL AFTER `best_single_wc_gf_per_game`,
  ADD COLUMN `best_single_wc_ga_per_game` decimal(6,4) DEFAULT NULL AFTER `best_single_wc_gf_per_game_tournament_id`,
  ADD COLUMN `best_single_wc_ga_per_game_tournament_id` int(11) DEFAULT NULL AFTER `best_single_wc_ga_per_game`;

ALTER TABLE `amiga_player_slice_at_event`
  ADD COLUMN `best_attack_awards` int(11) NOT NULL DEFAULT 0 AFTER `clean_sheets_victims`,
  ADD COLUMN `best_defense_awards` int(11) NOT NULL DEFAULT 0 AFTER `best_attack_awards`,
  ADD COLUMN `best_single_wc_gf_per_game` decimal(6,4) DEFAULT NULL AFTER `best_defense_awards`,
  ADD COLUMN `best_single_wc_gf_per_game_tournament_id` int(11) DEFAULT NULL AFTER `best_single_wc_gf_per_game`,
  ADD COLUMN `best_single_wc_ga_per_game` decimal(6,4) DEFAULT NULL AFTER `best_single_wc_gf_per_game_tournament_id`,
  ADD COLUMN `best_single_wc_ga_per_game_tournament_id` int(11) DEFAULT NULL AFTER `best_single_wc_ga_per_game`;

INSERT IGNORE INTO `amiga_wc_hof_present` (`id`) VALUES (1);