# Download KOOL site fonts (latin woff2) into site/public_html/fonts/
# Sources: @fontsource npm mirrors on jsDelivr (OFL/SIL licensed families from Google Fonts)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$fontsDir = Join-Path $root 'site\public_html\fonts'
New-Item -ItemType Directory -Force -Path $fontsDir | Out-Null

$packages = @(
    @{ pkg = '@fontsource/exo-2@5.2.8'; prefix = 'exo-2'; weights = @(500, 600, 700) },
    @{ pkg = '@fontsource/ibm-plex-sans@5.2.8'; prefix = 'ibm-plex-sans'; weights = @(400, 500, 600, 700) },
    @{ pkg = '@fontsource/ibm-plex-mono@5.1.0'; prefix = 'ibm-plex-mono'; weights = @(400, 500) }
)

$downloaded = @()
foreach ($fam in $packages) {
    foreach ($w in $fam.weights) {
        $remoteName = '{0}-latin-{1}-normal.woff2' -f $fam.prefix, $w
        $localName = $remoteName
        $url = 'https://cdn.jsdelivr.net/npm/{0}/files/{1}' -f $fam.pkg, $remoteName
        $dest = Join-Path $fontsDir $localName
        Write-Host "GET $url"
        Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
        $downloaded += [PSCustomObject]@{ Family = $fam.prefix; Weight = $w; File = $localName }
    }
}

$cssPath = Join-Path $root 'site\public_html\stylesheets\k2-fonts.css'
$familyNames = @{
    'exo-2' = 'Exo 2'
    'ibm-plex-sans' = 'IBM Plex Sans'
    'ibm-plex-mono' = 'IBM Plex Mono'
}
$lines = @(
    '/* Self-hosted fonts — generated by scripts/sync_self_hosted_fonts.ps1 */',
    '/* Licenses: site/public_html/fonts/LICENSES.md */',
    ''
)
foreach ($fam in $packages) {
    $display = $familyNames[$fam.prefix]
    foreach ($w in $fam.weights) {
        $file = '{0}-latin-{1}-normal.woff2' -f $fam.prefix, $w
        $lines += '@font-face {'
        $lines += ('  font-family: "{0}";' -f $display)
        $lines += '  font-style: normal;'
        $lines += ('  font-weight: {0};' -f $w)
        $lines += '  font-display: swap;'
        $lines += ('  src: url("../fonts/{0}") format("woff2");' -f $file)
        $lines += '}'
        $lines += ''
    }
}
Set-Content -Path $cssPath -Value ($lines -join "`n") -Encoding UTF8
Write-Host "Wrote $cssPath ($($downloaded.Count) files)"
