"""Manual video rows added by Dagh (not from harvest)."""

from __future__ import annotations

from scripts.amiga.tournament_videos.constants import CSV_COLUMNS

MANUAL_ROWS: list[dict[str, str]] = [
    {
        "youtube_id": "9NLKNUdVXNc",
        "title": "Kick Off Association World Cup 2001 - Dartford, Kent, UK",
        "duration_sec": "5581",
        "guessed_tournament_id": "26",
        "tournament_guess_label": "World Cup I (Dartford)",
        "year": "2001",
        "kind": "atmosphere",
        "stage": "atmosphere",
        "source": "manual",
        "verified": "Y",
        "confidence": "high",
        "notes": "WC 2001 atmosphere (Dagh add Jun 2026)",
    },
    {
        "youtube_id": "okZYaLT-Mwk",
        "title": "KOA World Cup 2003 - Airport Gathering, the Flight, in Holland & Practice",
        "duration_sec": "356",
        "guessed_tournament_id": "115",
        "tournament_guess_label": "World Cup III (Groningen)",
        "year": "2003",
        "kind": "atmosphere",
        "stage": "atmosphere",
        "source": "manual",
        "verified": "Y",
        "confidence": "high",
        "notes": "WC 2003 atmosphere (Dagh add Jun 2026)",
    },
    {
        "youtube_id": "6WmRIQvvcP8",
        "title": "Wonka celebration ko2 athens 2002",
        "duration_sec": "26",
        "guessed_tournament_id": "66",
        "tournament_guess_label": "World Cup II (Athens)",
        "year": "2002",
        "kind": "atmosphere",
        "stage": "atmosphere",
        "source": "manual",
        "verified": "Y",
        "confidence": "high",
        "notes": "WC 2002 Athens Wonka celebration (Dagh add Jul 2026)",
    },
    {
        "youtube_id": "4k4Ew4ghbZw",
        "title": "Kick Off Association 1st ever UK Championship 2002 - Gloucester, UK",
        "duration_sec": "8216",
        "guessed_tournament_id": "32",
        "tournament_guess_label": "Gloucester I",
        "year": "2002",
        "kind": "stream",
        "stage": "stream",
        "source": "manual",
        "verified": "Y",
        "confidence": "high",
        "notes": "UKC 2002 long coverage (~2h15m); atmosphere + in-event game clips; not one game",
    },
    {
        "youtube_id": "RSR8jP27V4c",
        "title": "KOA London International 2009 - Gianni (Team A) vs Dagh (Team B) - 1st part",
        "duration_sec": "340",
        "guessed_tournament_id": "371",
        "tournament_guess_label": "London XXIII",
        "year": "2009",
        "kind": "match",
        "score": "4-7",
        "player_a_guess": "Gianni T",
        "player_a_id_guess": "149",
        "player_b_guess": "Dagh N",
        "player_b_id_guess": "73",
        "game_id_guess": "14809",
        "relation_group": "london-xxiii-14809-gianni-dagh",
        "relation": "canonical",
        "source": "manual",
        "verified": "Y",
        "confidence": "high",
        "notes": "Game split across two uploads; part 1",
    },
    {
        "youtube_id": "eCLyltJxOiI",
        "title": "KOA London International 2009 - Gianni (Team A) vs Dagh (Team B) - 2nd part",
        "duration_sec": "318",
        "guessed_tournament_id": "371",
        "tournament_guess_label": "London XXIII",
        "year": "2009",
        "kind": "match",
        "score": "4-7",
        "player_a_guess": "Gianni T",
        "player_a_id_guess": "149",
        "player_b_guess": "Dagh N",
        "player_b_id_guess": "73",
        "game_id_guess": "14809",
        "relation_group": "london-xxiii-14809-gianni-dagh",
        "relation": "alternate_recording",
        "source": "manual",
        "verified": "Y",
        "confidence": "high",
        "notes": "Game split across two uploads; part 2",
    },
    {
        "youtube_id": "ipDxCXtqa8g",
        "title": "Closing stages of KOA UK Champs 2005 Title outcome decider",
        "duration_sec": "134",
        "guessed_tournament_id": "157",
        "tournament_guess_label": "Stoke",
        "year": "2005",
        "kind": "atmosphere",
        "stage": "atmosphere",
        "game_id_guess": "5622",
        "source": "manual",
        "verified": "Y",
        "confidence": "high",
        "notes": "Atmosphere around game 5622 (Rikki F vs Steve C 4-5)",
    },
    # @KO2CV_TV/streams — Steve C live archives (manual map Jun 2026; no auto-matcher)
    {
        "youtube_id": "p1HKrcUCHMA",
        "title": "Kick Off 2 World Cup 2025 - Milan, Italy - Day 1",
        "duration_sec": "26190",
        "guessed_tournament_id": "25",
        "tournament_guess_label": "World Cup XXIII (Milan)",
        "year": "2025",
        "kind": "stream",
        "stage": "day1",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "KO2CV_TV live stream archive",
    },
    {
        "youtube_id": "6DTqboK7kQU",
        "title": "Kick Off 2 World Cup 2025 - Milan, Italy - Day 2",
        "duration_sec": "37557",
        "guessed_tournament_id": "25",
        "tournament_guess_label": "World Cup XXIII (Milan)",
        "year": "2025",
        "kind": "stream",
        "stage": "day2",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "KO2CV_TV live stream archive",
    },
    {
        "youtube_id": "khhvhsnUFz4",
        "title": "Kick Off 2 UK Championship 2025",
        "duration_sec": "22826",
        "guessed_tournament_id": "23",
        "tournament_guess_label": "Nottingham II",
        "year": "2025",
        "kind": "stream",
        "stage": "stream",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "UK Champs 2025 (Nottingham II in DB)",
    },
    {
        "youtube_id": "_cRSiEAhUps",
        "title": "Kick Off 2 UK Championship 2026 (Nottingham III)",
        "duration_sec": "",
        "guessed_tournament_id": "607",
        "tournament_guess_label": "Nottingham III",
        "year": "2026",
        "kind": "stream",
        "stage": "stream",
        "game_link_mode": "stream_map",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "UK Champs 2026 stream; 15 forum timestamps (H:MM) mapped in video_game_links.csv (partial coverage)",
    },
    {
        "youtube_id": "diCwBurumT4",
        "title": "Kick Off 2 World Cup 2024 - Nottingham UK - Day 1",
        "duration_sec": "22161",
        "guessed_tournament_id": "20",
        "tournament_guess_label": "World Cup XXII (Nottingham)",
        "year": "2024",
        "kind": "stream",
        "stage": "day1",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "KO2CV_TV live stream archive",
    },
    {
        "youtube_id": "On9zBSdJQlQ",
        "title": "Kick Off 2 World Cup 2024 - Nottingham UK - Day 2",
        "duration_sec": "33863",
        "guessed_tournament_id": "20",
        "tournament_guess_label": "World Cup XXII (Nottingham)",
        "year": "2024",
        "kind": "stream",
        "stage": "day2",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "KO2CV_TV live stream archive",
    },
    {
        "youtube_id": "xm374O_wiZg",
        "title": "Kick Off 2 UK Championship - June 2024 - Preston",
        "duration_sec": "23886",
        "guessed_tournament_id": "18",
        "tournament_guess_label": "Preston I",
        "year": "2024",
        "kind": "stream",
        "stage": "stream",
        "relation_group": "ukc2024-preston-live",
        "relation": "canonical",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "Full UKC 2024 Preston stream (~6h38m)",
    },
    {
        "youtube_id": "IET9OrdGI2A",
        "title": "Kick Off 2 UK Championship - June 2024 - Preston",
        "duration_sec": "1294",
        "guessed_tournament_id": "18",
        "tournament_guess_label": "Preston I",
        "year": "2024",
        "kind": "stream",
        "stage": "stream",
        "relation_group": "ukc2024-preston-live",
        "relation": "alternate_recording",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "Short Preston 2024 clip (~22m); same event as xm374O_wiZg",
    },
    {
        "youtube_id": "RuatSO1izEM",
        "title": "Kick Off 2 World Cup Live Stream - Nov 2023 - Malaga, Spain. Day 1.",
        "duration_sec": "22529",
        "guessed_tournament_id": "16",
        "tournament_guess_label": "World Cup XXI (Torremolinos)",
        "year": "2023",
        "kind": "stream",
        "stage": "day1",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "KO2CV_TV live stream archive (Malaga/Torremolinos WC)",
    },
    {
        "youtube_id": "Dc5AEKcyCxg",
        "title": "Kick Off 2 World Cup Live Stream - Nov 2023 - Malaga, Spain. Day 2.",
        "duration_sec": "40631",
        "guessed_tournament_id": "16",
        "tournament_guess_label": "World Cup XXI (Torremolinos)",
        "year": "2023",
        "kind": "stream",
        "stage": "day2",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "KO2CV_TV live stream archive (Malaga/Torremolinos WC)",
    },
    {
        "youtube_id": "NO8Tg5FOn5E",
        "title": "KickOff2 World Cup Live Stream - 5 Nov 2022",
        "duration_sec": "9663",
        "guessed_tournament_id": "14",
        "tournament_guess_label": "World Cup XX (Athens)",
        "year": "2022",
        "kind": "stream",
        "stage": "day1",
        "relation_group": "wc2022-athens-day1-stream",
        "relation": "canonical",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "WC 2022 Athens day 1 live (~2h41m)",
    },
    {
        "youtube_id": "KJkK9TnRshA",
        "title": "Kick Off 2 World Cup Live Stream - 5 Nov 2022",
        "duration_sec": "9041",
        "guessed_tournament_id": "14",
        "tournament_guess_label": "World Cup XX (Athens)",
        "year": "2022",
        "kind": "stream",
        "stage": "day1",
        "relation_group": "wc2022-athens-day1-stream",
        "relation": "alternate_recording",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "Parallel/restart day-1 stream; same WC XX Athens",
    },
    {
        "youtube_id": "JEJ9zEviss8",
        "title": "Kick Off 2 World Cup Live Stream - 6 Nov 2022",
        "duration_sec": "37031",
        "guessed_tournament_id": "14",
        "tournament_guess_label": "World Cup XX (Athens)",
        "year": "2022",
        "kind": "stream",
        "stage": "day2",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "WC 2022 Athens day 2 live (~10h17m)",
    },
    {
        "youtube_id": "D2d9iP_-D2M",
        "title": "Kick Off 2 World Cup 2019 - Day 0.",
        "duration_sec": "13054",
        "guessed_tournament_id": "9",
        "tournament_guess_label": "World Cup XIX (Bremen)",
        "year": "2019",
        "kind": "stream",
        "stage": "day0",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "Pre-event / setup day Bremen 2019",
    },
    {
        "youtube_id": "Zrk_vEvuulU",
        "title": "Kick Off 2 World Cup 2019 - Day 1.",
        "duration_sec": "42926",
        "guessed_tournament_id": "9",
        "tournament_guess_label": "World Cup XIX (Bremen)",
        "year": "2019",
        "kind": "stream",
        "stage": "day1",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "KO2CV_TV live stream archive",
    },
    {
        "youtube_id": "iVAupwlIDp4",
        "title": "Kick Off 2 World Cup 2019 - Day 2",
        "duration_sec": "33517",
        "guessed_tournament_id": "9",
        "tournament_guess_label": "World Cup XIX (Bremen)",
        "year": "2019",
        "kind": "stream",
        "stage": "day2",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "KO2CV_TV live stream archive",
    },
    {
        "youtube_id": "yIZRVZ3veYA",
        "title": "World Cup 2016 in Milan",
        "duration_sec": "22533",
        "guessed_tournament_id": "596",
        "tournament_guess_label": "World Cup XVI (Milan)",
        "year": "2016",
        "kind": "stream",
        "stage": "stream",
        "relation_group": "wc2016-milan-live",
        "relation": "canonical",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "Longest WC 2016 Milan live segment (~6h15m)",
    },
    {
        "youtube_id": "2HPw0z-6CW0",
        "title": "World Cup 2016 in Milan",
        "duration_sec": "17124",
        "guessed_tournament_id": "596",
        "tournament_guess_label": "World Cup XVI (Milan)",
        "year": "2016",
        "kind": "stream",
        "stage": "stream",
        "relation_group": "wc2016-milan-live",
        "relation": "alternate_recording",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "WC 2016 Milan live segment (~4h45m)",
    },
    {
        "youtube_id": "30GQitGK0HU",
        "title": "World Cup 2016 in Milan",
        "duration_sec": "9129",
        "guessed_tournament_id": "596",
        "tournament_guess_label": "World Cup XVI (Milan)",
        "year": "2016",
        "kind": "stream",
        "stage": "stream",
        "relation_group": "wc2016-milan-live",
        "relation": "alternate_recording",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "WC 2016 Milan live segment (~2h32m)",
    },
    {
        "youtube_id": "hgg5wtwuA-Y",
        "title": "World Cup 2016 in Milan",
        "duration_sec": "4711",
        "guessed_tournament_id": "596",
        "tournament_guess_label": "World Cup XVI (Milan)",
        "year": "2016",
        "kind": "stream",
        "stage": "stream",
        "relation_group": "wc2016-milan-live",
        "relation": "alternate_recording",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "WC 2016 Milan live segment (~1h18m)",
    },
    {
        "youtube_id": "p6q8vJYMny4",
        "title": "World Cup 2016 in Milan",
        "duration_sec": "2442",
        "guessed_tournament_id": "596",
        "tournament_guess_label": "World Cup XVI (Milan)",
        "year": "2016",
        "kind": "stream",
        "stage": "stream",
        "relation_group": "wc2016-milan-live",
        "relation": "alternate_recording",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "WC 2016 Milan live segment (~41m)",
    },
    {
        "youtube_id": "Z9HohavTlzY",
        "title": "World Cup 2016 in Milan",
        "duration_sec": "1598",
        "guessed_tournament_id": "596",
        "tournament_guess_label": "World Cup XVI (Milan)",
        "year": "2016",
        "kind": "stream",
        "stage": "stream",
        "relation_group": "wc2016-milan-live",
        "relation": "alternate_recording",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "WC 2016 Milan live segment (~27m)",
    },
    {
        "youtube_id": "mjXv8QDpCn4",
        "title": "World Cup 2016 in Milan",
        "duration_sec": "982",
        "guessed_tournament_id": "596",
        "tournament_guess_label": "World Cup XVI (Milan)",
        "year": "2016",
        "kind": "stream",
        "stage": "stream",
        "relation_group": "wc2016-milan-live",
        "relation": "alternate_recording",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "WC 2016 Milan live segment (~16m)",
    },
    {
        "youtube_id": "eH0JQOX4XCw",
        "title": "World Cup 2016 in Milan",
        "duration_sec": "89",
        "guessed_tournament_id": "596",
        "tournament_guess_label": "World Cup XVI (Milan)",
        "year": "2016",
        "kind": "stream",
        "stage": "stream",
        "relation_group": "wc2016-milan-live",
        "relation": "alternate_recording",
        "source": "manual",
        "source_channel": "ko2cv",
        "verified": "Y",
        "confidence": "high",
        "notes": "WC 2016 Milan live fragment (~1m)",
    },
]


def merge_manual_rows(rows: list[dict[str, str]]) -> int:
    """Append MANUAL_ROWS when youtube_id is not already in review.csv."""
    existing = {r.get("youtube_id") for r in rows}
    added = 0
    for raw in MANUAL_ROWS:
        yt = raw["youtube_id"]
        if yt in existing:
            continue
        row = {col: "" for col in CSV_COLUMNS}
        row.update(raw)
        rows.append(row)
        existing.add(yt)
        added += 1
    return added