-- Surgical: giant_slayer only (gen_milestone_chrono_sql.py)
-- Active #1 = highest rating among players with rated game in last 365d UTC
-- (or either player in the current game). Run after DELETE below.
DELETE FROM `player_milestones` WHERE `milestone_key` = 'giant_slayer';

INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (263, 'giant_slayer', '2017-06-09 22:36:30', 1, 'game', 12, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (257, 'giant_slayer', '2017-06-18 18:01:35', 1, 'game', 81, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (237, 'giant_slayer', '2017-06-18 22:24:16', 1, 'game', 98, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (250, 'giant_slayer', '2017-06-20 12:47:01', 1, 'game', 105, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (285, 'giant_slayer', '2017-06-27 21:04:50', 1, 'game', 177, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (260, 'giant_slayer', '2017-11-05 21:58:51', 1, 'game', 936, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (291, 'giant_slayer', '2017-11-05 22:29:38', 1, 'game', 940, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (255, 'giant_slayer', '2018-09-24 14:46:29', 1, 'game', 2526, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (304, 'giant_slayer', '2018-10-03 20:33:52', 1, 'game', 2671, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (318, 'giant_slayer', '2018-11-06 18:53:11', 1, 'game', 2998, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (272, 'giant_slayer', '2018-12-04 23:02:37', 1, 'game', 3390, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (316, 'giant_slayer', '2019-01-07 13:49:59', 1, 'game', 3899, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (256, 'giant_slayer', '2019-02-28 23:05:09', 1, 'game', 4822, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (328, 'giant_slayer', '2019-04-28 23:28:31', 1, 'game', 5717, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (261, 'giant_slayer', '2019-09-13 20:58:59', 1, 'game', 7458, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (248, 'giant_slayer', '2019-09-26 12:20:58', 1, 'game', 7816, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (349, 'giant_slayer', '2019-12-01 22:20:47', 1, 'game', 8953, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (274, 'giant_slayer', '2019-12-04 22:57:55', 1, 'game', 8991, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (384, 'giant_slayer', '2020-11-13 00:11:06', 1, 'game', 17091, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (385, 'giant_slayer', '2021-03-10 23:59:11', 1, 'game', 22000, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (433, 'giant_slayer', '2022-02-24 23:48:55', 1, 'game', 32537, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (536, 'giant_slayer', '2025-06-27 10:47:20', 1, 'game', 65229, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (537, 'giant_slayer', '2025-07-15 22:24:35', 1, 'game', 65727, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (344, 'giant_slayer', '2025-09-13 00:04:58', 1, 'game', 67335, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (582, 'giant_slayer', '2025-09-23 21:12:47', 1, 'game', 67602, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (550, 'giant_slayer', '2025-10-10 15:56:53', 1, 'game', 68070, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (691, 'giant_slayer', '2025-10-17 16:13:05', 1, 'game', 68296, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (576, 'giant_slayer', '2025-10-26 20:01:37', 1, 'game', 68577, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (577, 'giant_slayer', '2025-11-23 18:49:15', 1, 'game', 69368, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (680, 'giant_slayer', '2026-02-06 18:47:00', 1, 'game', 71585, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (710, 'giant_slayer', '2026-02-16 17:04:35', 1, 'game', 72040, NULL, NULL, NULL);
