-- Generated by scripts/oneoff/gen_milestone_year_in_heaven_sql.py
-- year_in_heaven: first calendar year with a rated game in all 52 UTC week slots.

INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (237, 'year_in_heaven', '2019-12-23 23:38:58', 2019, 'game', 9193, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (260, 'year_in_heaven', '2020-12-21 00:05:19', 2020, 'game', 18478, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (263, 'year_in_heaven', '2018-12-24 23:08:16', 2018, 'game', 3669, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (344, 'year_in_heaven', '2021-12-21 21:59:38', 2021, 'game', 30277, NULL, NULL, NULL);
INSERT INTO `player_milestones` (`player_id`, `milestone_key`, `achieved_at`, `value`, `source_kind`, `source_game_id`, `source_league_kind`, `source_period_type`, `source_period_start`) VALUES (537, 'year_in_heaven', '2025-12-22 15:18:02', 2025, 'game', 70153, NULL, NULL, NULL);
